/**
 * The PreToolUse decision protocol shared by every guard hook.
 *
 * A hook says nothing to let the normal permission flow apply, `ask` to escalate to the user, or
 * `deny` to block. Every path exits 0: a hook signals through its JSON, never through its exit
 * code, and a broken hook must never get in the way of the work.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');

/** No output => the normal permission flow applies. */
function approve() {
  process.exit(0);
}

function decide(permissionDecision, reason) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision,
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

/** Escalate to the user with a reason they can act on. */
const requestConfirmation = (reason) => decide('ask', reason);

/** Block the tool call outright. */
const deny = (reason) => decide('deny', reason);

/** The hook payload from stdin, or null when there is nothing usable to read. */
function readPayload() {
  const raw = fs.readFileSync(0, 'utf8');
  if (!raw.trim()) return null;
  return JSON.parse(raw);
}

module.exports = { approve, requestConfirmation, deny, readPayload };
