/**
 * Check: a `git commit` / `git push` that lands on the repository's default branch.
 *
 * The convention (skill `branch-flow`) is: the default branch is protected, every change goes
 * through a `feature/*` or `fix/*` branch and a PR. This check makes the rule visible exactly when
 * it is about to be broken.
 *
 * No `git` subprocess at all: the current branch and the default branch are read straight out of
 * the `.git` directory (three `git` calls used to cost ~150-180ms on every tool call), so the
 * common case — a command that is not a commit/push — is one regex, and the worst case is two or
 * three small file reads.
 *
 * Detection works per chained command, not on the line as a whole. Scanning the whole line was
 * both too lax and too eager: `git push --dry-run origin main && git push origin main` looked like
 * a dry run and was approved, while `git log --grep=commit` looked like a commit and prompted.
 * `tools/guard-shell.test.mjs` pins that behaviour.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { parseSegments } = require('./segments');

/**
 * Blank out the values of message-carrying flags, including combined ones (-am, -sm), so a branch
 * name inside a commit message is never read as a ref. The short form is capped at a real flag
 * cluster and may not start mid-word: `-[a-zA-Z]*m` also matched `-upstream`, which then swallowed
 * the token after `--set-upstream` and could have hidden the ref that follows it.
 */
function scrubMessages(command) {
  return command.replace(
    /(--message|--reuse-message|--file|-F|(?:(?<![-\w])-[a-zA-Z]{0,3}m))(\s*=?\s*)("[^"]*"|'[^']*'|\S+)/g,
    (_, flag, sep) => `${flag}${sep}MSG`,
  );
}

/** git's own options that swallow the next token, so it can never be mistaken for the subcommand. */
const GIT_VALUE_FLAGS = new Set([
  '-C', '-c', '--git-dir', '--work-tree', '--namespace', '--exec-path', '--config-env', '--super-prefix',
]);

/** `git`, `git.exe`, `/usr/bin/git`, `$(git`, … */
function isGitToken(token) {
  return /(?:^|[/\\(])git(?:\.exe)?$/i.test(token.replace(/^\$/, ''));
}

/**
 * The git call inside one segment: its subcommand, its `-C` path and its own arguments. Global
 * options are skipped so the subcommand is read from the position where git itself reads it.
 */
function parseGitCall(tokens) {
  const start = tokens.findIndex(isGitToken);
  if (start < 0) return null;

  const args = tokens.slice(start + 1);
  let dashC = null;
  let subcommand = null;
  for (let i = 0; i < args.length; i += 1) {
    if (GIT_VALUE_FLAGS.has(args[i])) {
      if (args[i] === '-C') dashC = args[i + 1] ?? null;
      i += 1;
    } else if (!args[i].startsWith('-')) {
      subcommand = args[i];
      break;
    }
  }
  return { subcommand, dashC, args };
}

/** A dry run changes nothing. `-n` is --dry-run for push, but --no-verify for commit. */
function isDryRun(call) {
  return call.args.includes('--dry-run') || (call.subcommand === 'push' && call.args.includes('-n'));
}

/** Every ref-ish part of a token: `HEAD:main`, `refs/heads/main` and `+main` all yield `main`. */
function refParts(token) {
  return token.replace(/^\+/, '').split(':').flatMap((part) => [part, ...part.split('/')]);
}

/**
 * `--all` and `--mirror` push every ref without naming any, so no amount of name matching can
 * prove they stay off the default branch.
 */
function pushesEveryRef(call) {
  return call.args.includes('--all') || call.args.includes('--mirror');
}

/** Walk up from `start` to the repo root and return its resolved .git directory. */
function findGitDir(start) {
  let dir = path.resolve(start);
  for (;;) {
    const candidate = path.join(dir, '.git');
    if (fs.existsSync(candidate)) {
      const stat = fs.statSync(candidate);
      if (stat.isDirectory()) return candidate;
      // A worktree or submodule: `.git` is a file containing `gitdir: <path>`.
      const pointer = fs.readFileSync(candidate, 'utf8').match(/^gitdir:\s*(.+)$/m);
      if (!pointer) return null;
      const resolved = path.resolve(dir, pointer[1].trim());
      return fs.existsSync(resolved) ? resolved : null;
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function readRef(gitDir, relative) {
  try {
    return fs.readFileSync(path.join(gitDir, relative), 'utf8').trim();
  } catch {
    return null;
  }
}

/** The checked-out branch, or null when HEAD is detached. */
function currentBranch(gitDir) {
  const head = readRef(gitDir, 'HEAD');
  const m = head && head.match(/^ref:\s*refs\/heads\/(.+)$/);
  return m ? m[1] : null;
}

/** The repo's default branch: origin/HEAD if it is set, else whichever of main/master exists. */
function defaultBranch(gitDir) {
  const originHead = readRef(gitDir, path.join('refs', 'remotes', 'origin', 'HEAD'));
  const symbolic = originHead && originHead.match(/^ref:\s*refs\/remotes\/origin\/(.+)$/);
  if (symbolic) return symbolic[1];

  // Some clones keep it in packed-refs / in the config-less form.
  const packed = readRef(gitDir, 'packed-refs') ?? '';
  const packedOrigin = packed.match(/^ref:\s*refs\/remotes\/origin\/(.+)$/m);
  if (packedOrigin) return packedOrigin[1];

  for (const candidate of ['main', 'master']) {
    if (readRef(gitDir, path.join('refs', 'heads', candidate))) return candidate;
    if (new RegExp(`\\srefs/heads/${candidate}$`, 'm').test(packed)) return candidate;
  }
  return null;
}

/** The confirmation reason when `command` commits or pushes onto the default branch, else null. */
function checkDefaultBranch(command, cwd) {
  const scan = scrubMessages(command);
  // Fast path for the overwhelming majority of tool calls: nothing here can be a commit or a push,
  // so it is one regex and no parsing at all.
  if (!/\b(?:commit|push)\b/.test(scan)) return null;

  // Only the calls that really run a commit/push, dry runs excluded one command at a time.
  const calls = parseSegments(scan)
    .map(parseGitCall)
    .filter((call) => call
      && (call.subcommand === 'commit' || call.subcommand === 'push')
      && !isDryRun(call));
  if (!calls.length) return null;

  const isCommit = calls.some((call) => call.subcommand === 'commit');
  const pushes = calls.filter((call) => call.subcommand === 'push');
  const isPush = pushes.length > 0;

  const repo = calls.find((call) => call.dashC)?.dashC || cwd;
  if (!repo || !fs.existsSync(repo)) return null;

  const gitDir = findGitDir(repo);
  if (!gitDir) return null;

  const current = currentBranch(gitDir);
  const fallback = defaultBranch(gitDir);
  if (!current || !fallback) return null;

  if (current !== fallback) {
    // On a working branch the remaining case is a push that reaches the default branch from here.
    const protectedBranch = 'the protected branch of this repo. The branch-flow convention says '
      + 'only a PR gets there (squash, green CI + 1 review). Confirm?';

    if (pushes.some(pushesEveryRef)) {
      return `This command pushes every ref (--all/--mirror), so it also pushes '${fallback}', `
        + protectedBranch;
    }
    // The branch name must be a whole ref part: `feature/main-cleanup` is not a push to `main`.
    if (pushes.some((call) => call.args.some((arg) => refParts(arg).includes(fallback)))) {
      return `This command pushes to '${fallback}', ${protectedBranch}`;
    }
    return null;
  }

  const action = isCommit && isPush ? 'commit and push' : isCommit ? 'commit' : 'push';
  return `You are on '${current}', this repo's default branch. The branch-flow convention forbids `
    + `a direct ${action} here: the way in is a feature/* or fix/* branch and a PR into `
    + `'${fallback}'. Confirm anyway?`;
}

module.exports = { checkDefaultBranch };
