/**
 * Check: an action with no undo, wherever it sits in the command line.
 *
 * The permission allow/deny list can only match a command *prefix*, so it is blind to the shape
 * that actually loses data: the destructive verb buried inside a longer line —
 * `docker exec -i db sqlcmd -Q "DROP DATABASE Sales"`, `docker compose down -v`,
 * `az group delete --yes`. This check reads the whole line, per chained command.
 *
 * No subprocess and no file system access at all: it is pure text analysis, so the common case
 * (a line with none of the danger words) is one regex and nothing else.
 *
 * The interesting half of the problem is the false positives. Four of them are worth naming,
 * because each one would have trained the user to click through the prompt:
 *
 *   - a *searcher*: `grep -rn "DROP TABLE" .` hunts for the danger, it does not do it. A segment
 *     whose command is a search tool is skipped whole.
 *   - a *comment*: `# then DROP DATABASE Sales` — `#` comments outside quotes are blanked, and so
 *     are `--` / block comments inside a quoted SQL string.
 *   - a *path*: `psql -f scripts/drop-old-tables.sql` names a file. Path-shaped tokens outside
 *     quotes are blanked (which is also why this check cannot see inside a script — see below).
 *   - a *read-only query*: `sqlcmd -Q "SELECT 'DROP TABLE ' + name FROM sys.tables"` generates
 *     text. Inside a quoted string, SQL string literals and whole read-only statements are blanked.
 *
 * Plus `--dry-run` / `--what-if` / `--help`, per chained command, which change nothing.
 *
 * Deliberately NOT detected: what a script or a migration *contains*. `./teardown.ps1` and
 * `psql -f drop.sql` are one token here; reading the file would mean I/O on every tool call, and
 * the risk is the user's own script, which they wrote. `tools/guard-shell.test.mjs` pins every
 * rule and every false positive above.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const { splitSegments } = require('./segments');

/**
 * Cheap gate. If none of these words is anywhere in the line, no rule below can fire, so the
 * overwhelming majority of tool calls cost exactly one regex.
 *
 * `purge_queue` / `delete_queue` are listed in full because `_` is a word character, so `\bpurge\b`
 * does not match inside them — the broker CLIs would have slipped straight through the gate.
 */
const DANGER_WORDS = /\b(?:drop|dropdb|dropuser|dropdatabase|truncate|flushall|flushdb|flush_all|prune|purge|purge_queue|delete|delete_queue|destroy|uninstall|remove|rm|down|nuke)\b/i;
/** A flag cluster carrying `-D`: force-delete. Case-sensitive, because `-d` is the safe form. */
const DANGER_FLAG = /(?<![-\w])-[a-zA-Z]*D[a-zA-Z]*(?![\w-])/;

const isDangerous = (text) => DANGER_WORDS.test(text) || DANGER_FLAG.test(text);

/** Commands that look for a string instead of acting on it: never destructive, whatever they find. */
const SEARCHERS = new Set([
  'grep', 'egrep', 'fgrep', 'rg', 'ripgrep', 'ack', 'ag', 'findstr', 'select-string', 'sls',
  'get-help', 'man', 'help', 'which', 'where', 'get-command',
]);

/** Flags that make the whole chained command a no-op. */
const NOOP_FLAGS = /(?<![-\w])(?:--dry-run|--dryrun|--dry_run|--what-if|--whatif|-whatif|--noop|--no-op|--help|--usage|--version)\b/i;

/** Extensions common enough that a bare `drop-tables.sql` is obviously a file, not a statement. */
const PATHISH = /^[^\s]*(?:[\\/][^\s]*|\.(?:sql|ps1|psm1|sh|bash|cmd|bat|js|mjs|cjs|ts|cs|csproj|sln|json|ya?ml|xml|md|txt|log|bak|tf|dockerfile))$/i;

/** Walk a segment once, reporting every quoted span (content only, quotes excluded). */
function quotedSpans(segment) {
  const spans = [];
  let quote = null;
  let start = 0;
  for (let i = 0; i < segment.length; i += 1) {
    const c = segment[i];
    if (quote && c === quote) {
      spans.push({ start, end: i });
      quote = null;
    } else if (!quote && (c === '"' || c === "'")) {
      quote = c;
      start = i + 1;
    }
  }
  return spans;
}

/** Replace a slice with spaces, so every remaining match keeps its original offset. */
function blank(text, start, end) {
  return text.slice(0, start) + ' '.repeat(Math.max(0, end - start)) + text.slice(end);
}

/** The executable of a segment, lowercased and stripped of any directory and extension. */
function leadingCommand(segment) {
  const match = segment.trim().match(/^[^\s]+/);
  if (!match) return '';
  return match[0]
    .replace(/^["']|["']$/g, '')
    .replace(/^.*[\\/]/, '')
    .replace(/\.(?:exe|cmd|bat|ps1)$/i, '')
    .toLowerCase();
}

/** `git grep` / `git log --grep=…` are searchers too, but the verb is the second token. */
function isSearcher(segment) {
  const command = leadingCommand(segment);
  if (SEARCHERS.has(command)) return true;
  if (command === 'git') {
    const verb = segment.trim().split(/\s+/)[1];
    return ['grep', 'log', 'show', 'blame', 'diff'].includes(verb);
  }
  return false;
}

/**
 * SQL statements that only read. A quoted string is cut at `;` and each statement that starts with
 * one of these is blanked, so `SELECT … FROM sys.tables WHERE name = 'DropLog'` is inert while
 * `SELECT 1; DROP TABLE x` is not.
 */
const READ_ONLY_SQL = /^\s*(?:select|with|explain|show|describe|desc|print|use|set)\b/i;

/**
 * Blank everything inside a segment that cannot be an instruction to destroy something:
 * comments, file paths, SQL string literals and read-only SQL statements. Offsets are preserved so
 * the result can still be reported against the original text.
 */
function prepare(segment) {
  let scan = segment;

  // 1. `#` comments outside quotes (bash and PowerShell), from a token boundary to end of line.
  {
    let quote = null;
    for (let i = 0; i < scan.length; i += 1) {
      const c = scan[i];
      if (quote) {
        if (c === quote) quote = null;
      } else if (c === '"' || c === "'") {
        quote = c;
      } else if (c === '#' && (i === 0 || /\s/.test(scan[i - 1]))) {
        const end = scan.indexOf('\n', i);
        scan = blank(scan, i, end < 0 ? scan.length : end);
      }
    }
  }

  // 2. Inside each quoted span: SQL comments, then SQL string literals, then read-only statements.
  for (const span of quotedSpans(scan)) {
    let body = scan.slice(span.start, span.end);
    const offset = span.start;

    body = body.replace(/--[^\n]*/g, (m) => ' '.repeat(m.length));
    body = body.replace(/\/\*[\s\S]*?\*\//g, (m) => ' '.repeat(m.length));
    // A single-quoted literal inside a double-quoted argument is data, not a statement.
    body = body.replace(/'[^']*'/g, (m) => ' '.repeat(m.length));

    let at = 0;
    for (const statement of body.split(';')) {
      if (READ_ONLY_SQL.test(statement)) {
        body = blank(body, at, at + statement.length);
      }
      at += statement.length + 1;
    }
    scan = scan.slice(0, offset) + body + scan.slice(offset + body.length);
  }

  // 3. Path-shaped tokens *outside* quotes: `scripts/drop-old.sql`, `./teardown.ps1`, `C:\db\x.bak`.
  {
    const inQuote = new Array(scan.length).fill(false);
    for (const span of quotedSpans(scan)) {
      for (let i = span.start; i < span.end; i += 1) inQuote[i] = true;
    }
    for (const m of scan.matchAll(/[^\s"']+/g)) {
      if (inQuote[m.index]) continue;
      if (PATHISH.test(m[0])) scan = blank(scan, m.index, m.index + m[0].length);
    }
  }

  return scan;
}

/** Every rule: a predicate over the prepared segment, and what the user is asked. */
const has = (re) => (scan) => re.test(scan);
const all = (...tests) => (scan) => tests.every((t) => t(scan));

const RULES = [
  {
    test: has(/\bdrop\s+(?:database|schema|table|keyspace|collection)\b/i),
    reason: 'This drops a database, schema or table. The data and the object definition are gone, '
      + 'and only a backup brings them back. Confirm?',
  },
  {
    test: has(/\b(?:dropdb|dropuser|dropDatabase)\b/i),
    reason: 'This drops a whole database through the database CLI. There is no undo. Confirm?',
  },
  {
    test: has(/\btruncate\s+(?:table\s+)?["'`[\w]/i),
    reason: 'This truncates a table: every row is removed, unlogged and without firing triggers. '
      + 'Confirm?',
  },
  {
    test: has(/\bdatabase\s+drop\b/i),
    reason: 'This is a migration tool dropping the target database. Every row in it goes, '
      + 'including anything not reproducible from a seed. Confirm?',
  },
  {
    test: has(/\bmigrations?\s+remove\b/i),
    reason: 'This deletes the last migration and rewrites the model snapshot. If the migration was '
      + 'already applied or pushed, removing it desynchronises the history. Confirm?',
  },
  {
    test: has(/\b(?:flushall|flush_all)\b/i),
    reason: 'This flushes EVERY key in EVERY database of the cache instance. Confirm?',
  },
  {
    test: has(/\bflushdb\b/i),
    reason: 'This flushes every key in the selected cache database. Confirm?',
  },
  {
    test: all(
      has(/\bdown\b/i),
      has(/(?<![-\w])(?:-{1,2}v(?:olumes)?)(?![\w-])/i),
      has(/\b(?:docker|docker-compose|compose|podman|podman-compose|nerdctl)\b/i),
    ),
    reason: 'This tears the compose stack down WITH its volumes, so the database and cache '
      + 'contents of the local environment are deleted, not just the containers. Confirm?',
  },
  {
    test: all(has(/\bprune\b/i), has(/\b(?:docker|podman|buildx|nerdctl)\b/i)),
    reason: 'This prunes container resources. Pruning takes everything that is not in use right '
      + 'now, which regularly includes volumes and images that were still wanted. Confirm?',
  },
  {
    test: has(/\bvolume\s+(?:rm|remove|delete|prune)\b/i),
    reason: 'This deletes a container volume, and with it whatever the container kept there. '
      + 'Confirm?',
  },
  {
    test: has(/\b(?:purge_queue|delete_queue|purge\s+queue|delete\s+queue|queue\s+purge|queue\s+delete)\b/i),
    reason: 'This purges or deletes a broker queue. Messages still in it are dropped, and any '
      + 'consumer bound to it stops receiving. Confirm?',
  },
  {
    test: all(has(/\bdelete\b/i), has(/(?<![-\w])az(?![\w-])/i)),
    reason: 'This deletes a cloud or Azure DevOps resource. Deletion there is server-side and '
      + 'immediate. Confirm?',
  },
  {
    test: all(has(/\bdelete\b/i), has(/\bkubectl\b/i)),
    reason: 'This deletes a Kubernetes resource. If it is not managed by a manifest in the repo, '
      + 'nothing recreates it. Confirm?',
  },
  {
    test: has(/\bhelm\s+(?:uninstall|delete)\b/i),
    reason: 'This uninstalls a Helm release, including the resources it owns. Confirm?',
  },
  {
    test: has(/\bterraform\s+destroy\b/i),
    reason: 'This destroys every resource in the Terraform state. Confirm?',
  },
  {
    test: has(/\baws\s+[\w-]+\s+delete-[\w-]+/i),
    reason: 'This deletes a cloud resource. Deletion there is server-side and immediate. Confirm?',
  },
  {
    test: has(/\bgh\s+(?:repo|release|secret|run|cache|gist)\s+delete\b/i),
    reason: 'This deletes something on the remote host, not locally. Confirm?',
  },
  {
    // Case-sensitive: `-D` force-deletes, `-d` refuses to delete an unmerged branch.
    test: all(
      has(/\bbranch\b/),
      (scan) => /(?<![-\w])-[a-zA-Z]*D[a-zA-Z]*(?![\w-])/.test(scan)
        || (/--delete\b/.test(scan) && /(?<![-\w])(?:--force|-f)(?![\w-])/.test(scan)),
    ),
    reason: 'This force-deletes a branch, unmerged commits included. If the branch was never '
      + 'pushed, those commits are only in the reflog. Confirm?',
  },
];

/** The confirmation reason for the first action with no undo in `command`, else null. */
function checkDestructive(command) {
  // Fast path: nothing here can be one of the rules.
  if (!isDangerous(command)) return null;

  for (const segment of splitSegments(command)) {
    if (isSearcher(segment)) continue;
    if (NOOP_FLAGS.test(segment)) continue;

    const scan = prepare(segment);
    // The preparation may have blanked the only occurrence (a comment, a path, a read-only query).
    if (!isDangerous(scan)) continue;

    const rule = RULES.find((r) => r.test(scan));
    if (rule) return rule.reason;
  }
  return null;
}

module.exports = { checkDestructive };
