/**
 * Splitting a shell command line into one segment per chained command (`a && b`, `a; b`, `a | b`).
 *
 * Two splitters on purpose, because the guards need opposite things from the quotes:
 *
 *   - `parseSegments` tokenizes and STRIPS quotes: the git check reads tokens, and
 *     `-c credential.helper='!gh auth git-credential' push` must still yield `push`.
 *   - `splitSegments` KEEPS quotes and their contents: the destructive check looks for the danger
 *     *inside* a quoted argument (`sqlcmd -Q "DROP TABLE x"`).
 *
 * In both, a separator inside quotes does not split. Neither is a shell parser: they only have to
 * keep separate commands apart. Whatever they get wrong costs an extra confirmation, never a
 * silent approval.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const isSeparator = (c) => c === ';' || c === '|' || c === '&' || c === '\n' || c === '\r';

/** One segment per chained command, each a list of tokens with quotes honoured and stripped. */
function parseSegments(command) {
  const segments = [];
  let tokens = [];
  let token = '';
  let quote = null;

  const endToken = () => { if (token) { tokens.push(token); token = ''; } };
  const endSegment = () => { endToken(); if (tokens.length) { segments.push(tokens); tokens = []; } };

  for (const c of command) {
    if (quote) {
      if (c === quote) quote = null;
      else token += c;
    } else if (c === '"' || c === "'") {
      quote = c;
    } else if (isSeparator(c)) {
      endSegment();
    } else if (c === ' ' || c === '\t' || c === '`') {
      // A backtick is PowerShell's escape and bash's command substitution: a token boundary, not a
      // command boundary — a `git push` inside backticks still pushes.
      endToken();
    } else {
      token += c;
    }
  }
  endSegment();
  return segments;
}

/** One segment per chained command, as raw text with quotes and their contents intact. */
function splitSegments(command) {
  const segments = [];
  let current = '';
  let quote = null;

  const push = () => { if (current.trim()) segments.push(current); current = ''; };

  for (const c of command) {
    if (quote) {
      current += c;
      if (c === quote) quote = null;
    } else if (c === '"' || c === "'") {
      quote = c;
      current += c;
    } else if (isSeparator(c)) {
      push();
    } else {
      current += c;
    }
  }
  push();
  return segments;
}

module.exports = { parseSegments, splitSegments };
