#Requires -Version 7
<#
.SYNOPSIS
    PostToolUse hook for Write / Edit: formats the file that was just touched, and nothing else.

.DESCRIPTION
    Formatting noise is the cheapest thing to remove from a review and the most expensive to argue
    about. Running the formatter on the single file the tool just wrote keeps every diff to the
    change itself, without the "reformat the world" commit that hides it.

    PowerShell rather than Node — the exception to the kit's rule — because the work here IS the
    Windows tooling: locating the project, deciding whether a formatter is configured, and invoking
    the SDK or the local package runner. There is no text analysis to be fast about, and this runs
    only after a Write or an Edit, not before every tool call.

    Three deliberate limits:

      * It formats ONLY the file named in the payload. Never the project, never the folder.
      * It does nothing at all when the tooling is not configured: no project file above the file,
        no .editorconfig, no formatter in the package manifest, no dependencies installed. A hook
        that formats with defaults nobody chose is worse than no hook, because it rewrites files
        the project deliberately left alone.
      * It never fails the tool call. Every path ends in `exit 0`, output is swallowed, and a
        formatter that is absent, broken or slow is simply skipped.

    Detection is version-agnostic: the formatter is whatever the project configures, discovered from
    the files on disk, and it is invoked through the local package runner so nothing is downloaded.

.PARAMETER DryRun
    Print the formatter invocation that would run instead of running it, and exit. This is how
    tools/format-on-edit.test.mjs asserts the routing without needing the SDK or a node_modules
    tree on the machine running the tests.

.NOTES
    Generated by Claude Code at the user's request.
#>
[CmdletBinding()]
param([switch]$DryRun)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Generated output and dependency trees are not ours to format.
$ExcludedPath = '[\\/](?:node_modules|bin|obj|dist|out|coverage|\.git|\.vs|\.next|\.nuxt|\.angular|packages|TestResults)[\\/]'

# The .NET formatter handles these; the project's own JavaScript/TypeScript formatter the rest.
$DotnetExt = @('.cs', '.vb', '.razor', '.cshtml')
$WebExt = @(
    '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.mts', '.cts',
    '.json', '.jsonc', '.css', '.scss', '.less', '.html', '.vue', '.svelte'
)

# A formatter configured in the package manifest, in any of the forms it is written in.
$WebFormatterConfig = @(
    '.prettierrc', '.prettierrc.json', '.prettierrc.jsonc', '.prettierrc.yml', '.prettierrc.yaml',
    '.prettierrc.json5', '.prettierrc.toml', '.prettierrc.js', '.prettierrc.cjs', '.prettierrc.mjs',
    'prettier.config.js', 'prettier.config.cjs', 'prettier.config.mjs', 'prettier.config.ts'
)

# Walk up at most this far. A file 20 levels below a project file is not in that project in any
# sense worth formatting, and an unbounded walk would hit the filesystem root on every edit.
$MaxDepth = 12

function Find-Ancestor {
    <# The nearest ancestor directory containing a file matching one of $Names, or $null. #>
    param([string]$From, [string[]]$Names)

    $dir = Split-Path -Parent $From
    for ($i = 0; $i -lt $MaxDepth -and $dir; $i++) {
        foreach ($name in $Names) {
            $hit = Get-ChildItem -LiteralPath $dir -Filter $name -File -Force -ErrorAction SilentlyContinue |
                Select-Object -First 1
            if ($hit) { return [pscustomobject]@{ Directory = $dir; File = $hit.FullName } }
        }
        $parent = Split-Path -Parent $dir
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return $null
}

function Invoke-Formatter {
    <# Run it, or print it under -DryRun. Output is swallowed: silent on success is the contract. #>
    param([string]$Exe, [string[]]$FormatterArgs, [string]$WorkingDirectory)

    if ($DryRun) {
        Write-Output "$Exe $($FormatterArgs -join ' ')"
        return
    }
    Push-Location -LiteralPath $WorkingDirectory
    try { & $Exe @FormatterArgs *> $null } finally { Pop-Location }
}

try {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

    $payload = $raw | ConvertFrom-Json
    $target = $payload.tool_input.file_path
    if ([string]::IsNullOrWhiteSpace($target)) { exit 0 }
    if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { exit 0 }

    $file = (Get-Item -LiteralPath $target).FullName
    if ($file -match $ExcludedPath) { exit 0 }
    $ext = [System.IO.Path]::GetExtension($file).ToLowerInvariant()

    if ($DotnetExt -contains $ext) {
        # Outside a project there is nothing to derive the style from.
        $project = Find-Ancestor -From $file -Names @('*.csproj', '*.vbproj', '*.fsproj')
        if (-not $project) { exit 0 }
        # No .editorconfig means the project never chose a style: formatting would invent one.
        if (-not (Find-Ancestor -From $file -Names @('.editorconfig'))) { exit 0 }
        if (-not (Get-Command dotnet -CommandType Application -ErrorAction SilentlyContinue)) { exit 0 }

        # `whitespace` is the fast subset: indentation and line endings, no analyzer run, so the
        # hook stays in the hundreds of milliseconds instead of rebuilding the project.
        Invoke-Formatter -Exe 'dotnet' -WorkingDirectory $project.Directory -FormatterArgs @(
            'format', 'whitespace', $project.File,
            '--include', $file,
            '--no-restore',
            '--verbosity', 'quiet'
        )
        exit 0
    }

    if ($WebExt -contains $ext) {
        $manifest = Find-Ancestor -From $file -Names @('package.json')
        if (-not $manifest) { exit 0 }

        # The project must actually configure a formatter — a config file, or a key in the manifest.
        $configured = [bool](Find-Ancestor -From $file -Names $WebFormatterConfig)
        if (-not $configured) {
            try {
                $package = Get-Content -LiteralPath $manifest.File -Raw | ConvertFrom-Json
                $configured = $null -ne $package.PSObject.Properties['prettier']
            } catch { $configured = $false }
        }
        if (-not $configured) { exit 0 }

        # The local package runner only: dependencies must already be installed, so a hook can
        # never trigger a download in the middle of a session.
        if (-not (Test-Path -LiteralPath (Join-Path $manifest.Directory 'node_modules') -PathType Container)) { exit 0 }
        if (-not (Get-Command npx -CommandType Application -ErrorAction SilentlyContinue)) { exit 0 }

        Invoke-Formatter -Exe 'npx' -WorkingDirectory $manifest.Directory -FormatterArgs @(
            '--no-install', 'prettier', '--write', $file
        )
        exit 0
    }

    # Any other extension: not ours to format.
    exit 0
} catch {
    # A hook that breaks must not break the edit that triggered it.
    exit 0
}
