/**
 * PostToolUse hook for Write / Edit: formats the file that was just touched, and nothing else.
 *
 * Formatting noise is the cheapest thing to remove from a review and the most expensive to argue
 * about. Running the formatter on the single file the tool just wrote keeps every diff to the
 * change itself, without the "reformat the world" commit that hides it.
 *
 * Node, not PowerShell: this runs after EVERY Write and Edit, and most of them touch a file no
 * formatter owns (markdown, SQL, YAML). Starting `pwsh` cost ~1.1s before deciding anything; here
 * an extension with no formatter is one string comparison and an exit, with no file system access
 * at all. A formatter process is spawned only when the project really configures one.
 *
 * Three deliberate limits:
 *
 *   - It formats ONLY the file named in the payload. Never the project, never the folder.
 *   - It does nothing at all when the tooling is not configured: no project file above the file,
 *     no .editorconfig, no formatter in the package manifest, no dependencies installed. A hook
 *     that formats with defaults nobody chose is worse than no hook, because it rewrites files the
 *     project deliberately left alone.
 *   - It never fails the tool call. Every path ends in exit 0, output is swallowed, and a formatter
 *     that is absent, broken or slow is simply skipped.
 *
 * Detection is version-agnostic: the formatter is whatever the project configures, discovered from
 * the files on disk, and it is invoked through the local package runner so nothing is downloaded.
 *
 * `--dry-run` prints the formatter invocation that would run instead of running it. That is how
 * tools/format-on-edit.test.mjs asserts the routing without the SDK or a node_modules tree.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const DRY_RUN = process.argv.includes('--dry-run');
const IS_WINDOWS = process.platform === 'win32';

/** Generated output and dependency trees are not ours to format. */
const EXCLUDED_PATH = /[\\/](?:node_modules|bin|obj|dist|out|coverage|\.git|\.vs|\.next|\.nuxt|\.angular|packages|TestResults)[\\/]/i;

/** The .NET formatter handles these; the project's own JavaScript/TypeScript formatter the rest. */
const DOTNET_EXT = new Set(['.cs', '.vb', '.razor', '.cshtml']);
const WEB_EXT = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.mts', '.cts',
  '.json', '.jsonc', '.css', '.scss', '.less', '.html', '.vue', '.svelte',
]);

/** A formatter configured in the package manifest, in any of the forms it is written in. */
const WEB_FORMATTER_CONFIG = [
  '.prettierrc', '.prettierrc.json', '.prettierrc.jsonc', '.prettierrc.yml', '.prettierrc.yaml',
  '.prettierrc.json5', '.prettierrc.toml', '.prettierrc.js', '.prettierrc.cjs', '.prettierrc.mjs',
  'prettier.config.js', 'prettier.config.cjs', 'prettier.config.mjs', 'prettier.config.ts',
];

/**
 * Walk up at most this far. A file 20 levels below a project file is not in that project in any
 * sense worth formatting, and an unbounded walk would hit the filesystem root on every edit.
 */
const MAX_DEPTH = 12;

const done = () => process.exit(0);

/** A name pattern: `*.csproj` matches by suffix, anything else exactly. Case-insensitive, as on Windows. */
function matcher(pattern) {
  const p = pattern.toLowerCase();
  return p.startsWith('*') ? (name) => name.toLowerCase().endsWith(p.slice(1)) : (name) => name.toLowerCase() === p;
}

/** The nearest ancestor directory holding a file that matches one of `patterns`, or null. */
function findAncestor(from, patterns) {
  const tests = patterns.map(matcher);
  let dir = path.dirname(from);
  for (let i = 0; i < MAX_DEPTH && dir; i += 1) {
    let entries = [];
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { /* unreadable: keep walking */ }
    for (const test of tests) {
      const hit = entries.find((e) => e.isFile() && test(e.name));
      if (hit) return { directory: dir, file: path.join(dir, hit.name) };
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

/** The executable on PATH, as `Get-Command -CommandType Application` would find it, or null. */
function onPath(name) {
  const exts = IS_WINDOWS ? ['.exe', '.cmd', '.bat', ''] : [''];
  for (const dir of (process.env.PATH ?? '').split(path.delimiter).filter(Boolean)) {
    for (const ext of exts) {
      const candidate = path.join(dir, name + ext);
      try { if (fs.statSync(candidate).isFile()) return candidate; } catch { /* not here */ }
    }
  }
  return null;
}

/** Run it, or print it under --dry-run. Output is swallowed: silent on success is the contract. */
function invoke(exe, args, cwd) {
  if (DRY_RUN) {
    process.stdout.write(`${path.basename(exe).replace(/\.(?:exe|cmd|bat)$/i, '')} ${args.join(' ')}\n`);
    return;
  }
  // A `.cmd` shim (npx on Windows) cannot be spawned without a shell; quote every argument.
  const viaShell = IS_WINDOWS && /\.(?:cmd|bat)$/i.test(exe);
  const argv = viaShell ? args.map((a) => `"${a}"`) : args;
  spawnSync(viaShell ? `"${exe}"` : exe, argv, {
    cwd, stdio: 'ignore', shell: viaShell, windowsHide: true, timeout: 25000,
  });
}

try {
  const raw = fs.readFileSync(0, 'utf8');
  if (!raw.trim()) done();

  const target = JSON.parse(raw)?.tool_input?.file_path;
  if (typeof target !== 'string' || !target.trim()) done();

  // The fast path, before any file system access: most edits touch a file no formatter owns.
  const ext = path.extname(target).toLowerCase();
  const isDotnet = DOTNET_EXT.has(ext);
  if (!isDotnet && !WEB_EXT.has(ext)) done();

  const file = path.resolve(target);
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) done();
  if (EXCLUDED_PATH.test(file)) done();

  if (isDotnet) {
    // Outside a project there is nothing to derive the style from.
    const project = findAncestor(file, ['*.csproj', '*.vbproj', '*.fsproj']);
    if (!project) done();
    // No .editorconfig means the project never chose a style: formatting would invent one.
    if (!findAncestor(file, ['.editorconfig'])) done();
    const dotnet = onPath('dotnet');
    if (!dotnet) done();

    // `whitespace` is the fast subset: indentation and line endings, no analyzer run, so the hook
    // stays in the hundreds of milliseconds instead of rebuilding the project.
    invoke(dotnet, [
      'format', 'whitespace', project.file, '--include', file, '--no-restore', '--verbosity', 'quiet',
    ], project.directory);
    done();
  }

  const manifest = findAncestor(file, ['package.json']);
  if (!manifest) done();

  // The project must actually configure a formatter — a config file, or a key in the manifest.
  let configured = Boolean(findAncestor(file, WEB_FORMATTER_CONFIG));
  if (!configured) {
    try {
      configured = Object.prototype.hasOwnProperty.call(JSON.parse(fs.readFileSync(manifest.file, 'utf8')), 'prettier');
    } catch {
      configured = false;
    }
  }
  if (!configured) done();

  // The local package runner only: dependencies must already be installed, so a hook can never
  // trigger a download in the middle of a session.
  const modules = path.join(manifest.directory, 'node_modules');
  if (!fs.existsSync(modules) || !fs.statSync(modules).isDirectory()) done();
  const npx = onPath('npx');
  if (!npx) done();

  invoke(npx, ['--no-install', 'prettier', '--write', file], manifest.directory);
  done();
} catch {
  // A hook that breaks must not break the edit that triggered it.
  done();
}
