/**
 * PreToolUse hook for Bash / PowerShell — the single entry point for every shell guard.
 *
 * Runs, on the same parsed payload:
 *
 *   - lib/default-branch.js — a `git commit` / `git push` landing on the repo's default branch;
 *   - lib/destructive.js    — an action with no undo, even buried in `docker exec`, `sqlcmd -Q` or a
 *                             pipeline, where a permission prefix cannot see it.
 *
 * One process instead of two because this runs before EVERY Bash/PowerShell tool call (the
 * PreToolUse matcher can only filter by tool name, not by command text): one Node start-up, one
 * stdin parse. Node, not PowerShell — the whole hook is ~150ms against ~370ms just to start `pwsh`.
 *
 * Both checks always run. When both fire (`git push origin main && docker compose down -v`), the
 * user gets one prompt carrying both reasons.
 *
 * It never blocks on its own: at most it escalates to the user (permissionDecision "ask"), and any
 * error lets the command through. Always exits 0.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const { approve, requestConfirmation, readPayload } = require('./lib/decision');
const { checkDefaultBranch } = require('./lib/default-branch');
const { checkDestructive } = require('./lib/destructive');

/** Run one check, isolated: a bug in one must not silence the other. */
function safely(check) {
  try {
    return check();
  } catch {
    return null;
  }
}

try {
  const payload = readPayload();
  const command = payload?.tool_input?.command;
  if (typeof command !== 'string' || !command.trim()) approve();

  const reasons = [
    safely(() => checkDefaultBranch(command, payload.cwd)),
    safely(() => checkDestructive(command)),
  ].filter(Boolean);

  if (reasons.length) requestConfirmation(reasons.join('\n\n'));
  approve();
} catch {
  // A bug in the hook must never get in the way of the work.
  approve();
}
