/**
 * PreToolUse hook for Write / Edit.
 *
 * A credential that reaches a file is already halfway to the remote: the next `git add -A` takes
 * it, and once it is in the history it stays there. This hook is the last cheap moment to stop it,
 * so unlike the two guards it does not ask — it **denies** the write and names the pattern and the
 * line, which is all the information needed to fix it.
 *
 * The catalogue is the one tools/validate.mjs already enforces on the kit's own files — provider
 * tokens, a cloud access key id, an API-key-shaped string, a password inside a connection string —
 * plus the two shapes a source file can carry that a config repo cannot: a private key block and a
 * signed token. Keeping the two lists in step matters: what the validator rejects in the repo is
 * exactly what must never be written into a project either.
 *
 * Node, not PowerShell: this runs before every Write and Edit, so ~150ms against ~370ms just to
 * start `pwsh`. No subprocess, no file system access beyond stdin — it only reads the text the tool
 * is about to write.
 *
 * Three false positives are the ones that decide whether the hook is bearable, because each one
 * fires on perfectly correct code:
 *
 *   - a *placeholder*: `Password=<your-password>`, `Password=changeme`, `AccountKey=***`.
 *   - a *variable reference*: `Password=$env:DB_PASSWORD`, `Password=${DB_PASSWORD}`,
 *     `Password=" + password`, `Password=%DB_PASS%` — the value is a hole, not a secret.
 *   - a *detector*: the regex or the grep that hunts for secrets contains, by construction, the
 *     very shapes it looks for. A line carrying regex syntax is read as a pattern, not a value, and
 *     a scanner file (this one, the validator) is skipped whole — otherwise the hook would make
 *     itself unmaintainable.
 *
 * Deliberately NOT detected: a high-entropy string with no recognisable shape (`ApiKey = "8f3c…"`).
 * Entropy scoring on every write is a false-positive machine — minified assets, hashes, base64
 * fixtures and GUIDs all score high — and the shapes above cover the credentials that actually
 * leak. `tools/secret-scan.test.mjs` pins every pattern and every exemption above.
 *
 * Always exits 0. The deny is the deliberate block; any internal error lets the write through.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');

/** No output => the normal permission flow applies. */
function approve() {
  process.exit(0);
}

function deny(reason) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

/**
 * The catalogue. `value` is the capture group holding the part that has to look like a real secret;
 * where there is no group the whole match is the value.
 */
const PATTERNS = [
  {
    label: 'a provider token',
    re: /\b(?:glsa_|ghp_|github_pat_|gho_|ghs_|ghu_|xoxb-|xoxp-|xapp-)[A-Za-z0-9_-]{8,}/g,
  },
  {
    label: 'a cloud access key id',
    re: /\bAKIA[0-9A-Z]{16}\b/g,
  },
  {
    label: 'an API-key-shaped string',
    re: /\bsk-(?:ant|proj|live|test)?-?[A-Za-z0-9_-]{20,}/g,
  },
  {
    label: 'a cloud API key',
    re: /\bAIza[0-9A-Za-z_-]{35}\b/g,
  },
  {
    label: 'a private key block',
    re: /-----BEGIN\s+(?:[A-Z]+\s+)?PRIVATE KEY-----/g,
  },
  {
    label: 'a signed token',
    re: /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g,
  },
  {
    label: 'a password in a connection string',
    // `|` is excluded from the value on purpose: a detector reads `Password=|Pwd=`, and a real
    // password never starts with an alternation.
    re: /\b(?:password|pwd|user\s+password)\s*=\s*(?!<)([^;'"\s|,)}\]]{3,})/gi,
    value: 1,
  },
  {
    label: 'a cloud access key in a connection string',
    re: /\b(?:accountkey|sharedaccesskey|shared_access_key|aws_secret_access_key|client_secret|clientsecret)\s*=\s*(?!<)([^;'"\s|,)}\]]{8,})/gi,
    value: 1,
  },
];

/**
 * A value that is a hole rather than a secret: an interpolation, an environment lookup, a string
 * concatenation, a mask, or one of the words everybody writes when they mean "put yours here".
 */
// Only the characters that genuinely mark a hole. `(`, `)`, `!` and `+` are deliberately absent:
// they occur in real passwords, and the concatenation case (`"…Password=" + pwd`) is already
// covered because the value may not contain a quote.
const INTERPOLATION = /[<>{}$%`\\]|\[\[|::/;
/** `@Model.Password`, `config.db.password`: a member access is a reference, not a literal. */
const MEMBER_ACCESS = /^@?[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+$/;
const PLACEHOLDER_WORD = new RegExp(
  '^(?:'
  + 'changeme|change[-_]me|replace(?:[-_]?me)?|todo|tbd|fixme|'
  + 'your[-_\\w]*|my[-_\\w]*|the[-_]\\w+|'
  + 'placeholder|redacted|removed|hidden|masked|omitted|'
  + 'dummy|fake|sample|example[-_\\w]*|test|testing|foo|bar|baz|'
  + 'secret|password|passwd|pwd|pass|token|apikey|api[-_]key|key|value|string|'
  + 'null|none|nil|empty|undefined'
  + ')$',
  'i',
);
/** `example`, `sample`, `redacted`… anywhere in the value: it is documentation, not a credential. */
const EXAMPLE_MARKER = /example|sample|placeholder|redacted|changeme|dummy|myuser|mypassword/i;
/** A mask: `***`, `xxxx`, `…`, `--`. */
const MASK = /^[*x.\-_•…\s]+$/i;

/**
 * `reference` is true only for the `key=value` patterns, where the value is a configuration slot
 * and a reference to it is the correct thing to write. It must NOT apply to the shape-matched
 * patterns: a signed token is three dot-separated word runs, which is exactly the shape of a
 * member access, and treating it as a reference let a real token straight through.
 */
function isPlaceholder(value, reference) {
  const v = value.trim().replace(/^["'`]|["'`]$/g, '');
  if (!v) return true;
  if (INTERPOLATION.test(v)) return true;
  if (MASK.test(v)) return true;
  if (PLACEHOLDER_WORD.test(v)) return true;
  if (EXAMPLE_MARKER.test(v)) return true;
  if (!reference) return false;
  if (MEMBER_ACCESS.test(v)) return true;
  // `env:DB_PASSWORD`, `ENV.DB_PASSWORD`, `process.env.DB_PASSWORD`, `Secrets:Db:Password`
  if (/^(?:env[.:]|process\.env|secrets?[.:]|vault[.:])/i.test(v)) return true;
  // A SCREAMING_SNAKE name is a variable, never a password anybody typed.
  if (/^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/.test(v)) return true;
  return false;
}

/**
 * A line that carries regex or search syntax is a *detector*: the pattern that hunts for the
 * secret, not the secret. Skipping it is what keeps a scanner, a test fixture list and a
 * `git grep` recipe writable.
 */
const DETECTOR_LINE = /\(\?[:<=!]|\[A-Za-z|\[a-zA-Z|\[0-9|\[\^|\\b|\\s|\\d|\\w|\{\d+,|matchAll|RegExp|Select-String|-Pattern\b|\bgrep\b|\brg\s+-|\bregex/i;

/** Files whose whole job is to carry these patterns. Scanning them would lock them. */
const SCANNER_FILE = /(?:^|[\\/])(?:hooks|tools)[\\/][\w.-]*(?:secret|leak|scan|validate|guard)[\w.-]*$/i;

/** The text a Write or an Edit is about to introduce — never the text it removes. */
function newText(input) {
  if (typeof input?.content === 'string') return input.content;
  if (typeof input?.new_string === 'string') return input.new_string;
  if (Array.isArray(input?.edits)) {
    return input.edits.map((e) => (typeof e?.new_string === 'string' ? e.new_string : '')).join('\n');
  }
  return null;
}

/** Show enough to find it, never the whole credential. */
function redact(value) {
  const v = value.trim();
  return v.length <= 10 ? v : `${v.slice(0, 6)}…${v.slice(-2)} (${v.length} chars)`;
}

try {
  const raw = fs.readFileSync(0, 'utf8');
  if (!raw.trim()) approve();

  const payload = JSON.parse(raw);
  const filePath = payload?.tool_input?.file_path ?? '';
  const text = newText(payload?.tool_input);
  if (typeof text !== 'string' || !text.trim()) approve();
  if (SCANNER_FILE.test(filePath)) approve();

  const findings = [];
  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (line.length > 4000) continue;           // a minified bundle is not hand-written config
    if (DETECTOR_LINE.test(line)) continue;

    for (const { label, re, value } of PATTERNS) {
      re.lastIndex = 0;
      for (const m of line.matchAll(re)) {
        const found = value ? m[value] : m[0];
        if (isPlaceholder(found, value !== undefined)) continue;
        findings.push(`  line ${i + 1}: ${label} — ${redact(found)}`);
        break;                                   // one finding per pattern per line is enough
      }
    }
    if (findings.length >= 8) break;
  }

  if (!findings.length) approve();

  const where = filePath ? ` into ${filePath.replace(/^.*[\\/]/, '')}` : '';
  deny(
    `This write would introduce a credential${where}:\n${findings.join('\n')}\n\n`
    + 'Blocked before it can reach the working tree, because git history keeps whatever it is '
    + 'given. Put the value in the platform\'s secret store (user secrets, a key vault, the '
    + 'pipeline\'s secret variables) and leave a reference in the file — an environment lookup, a '
    + 'configuration key, or an explicit `<placeholder>`. If this really is a placeholder or a '
    + 'detection pattern, make it look like one and the write goes through.',
  );
} catch {
  // A bug in the hook must never get in the way of the work.
  approve();
}
