/**
 * SessionStart hook: at most five lines saying where the work stands.
 *
 * The first question of every session is the same one — which branch am I on, is the tree dirty,
 * what did I last commit, am I in step with the remote, what is this branch for — and answering it
 * costs a handful of tool calls and a chunk of context every time. Five lines of orientation,
 * injected once, replace them.
 *
 * The whole design is about not being felt at session start:
 *
 *   1. Node, ~150ms against ~370ms just to start `pwsh`.
 *   2. Cached. A snapshot lands in ~/.claude/.session-brief-cache.json, keyed by repository, the
 *      same way statusline.js persists its rate-limit snapshot; inside the TTL the brief is a
 *      single small file read. Resuming, compacting and clearing all re-fire this hook, so without
 *      a cache the cost would repeat all session long.
 *   3. Disk before subprocess. Branch, last commit and the upstream ref are read straight out of
 *      `.git`, exactly as guard-default-branch.js reads HEAD. Only the two facts that genuinely
 *      need the index — how dirty the tree is, and by how much the upstream diverges — cost one
 *      `git status` call, bounded by a hard timeout and skipped entirely if it fails.
 *   4. No network, ever. Nothing here reaches a remote, so a session on a train starts as fast as
 *      one in the office.
 *
 * That last rule is why the "open PR for this branch" line is not computed: it can only come from
 * the host, and the cheapest honest lookup is still a network round trip. Instead the brief prints
 * it when something else has left it in the cache under `pr` — the documented slot for the ALM
 * commands, which already talk to the host and can afford to. Until then the line is simply
 * absent, which is the rule for every fact here: a line that cannot be determined is not printed,
 * and nothing is ever guessed.
 *
 * The work item is derived offline, from the branch name, because that is where the convention
 * puts it.
 *
 * Always exits 0, and prints nothing at all rather than an error.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const zlib = require('zlib');
const { spawnSync } = require('child_process');

/**
 * Beside the statusline's own snapshot, in the Claude Code configuration directory — honouring
 * CLAUDE_CONFIG_DIR, Claude Code's own variable, so a relocated configuration keeps its cache with
 * it (and so the tests can point it at a temp directory instead of the real one).
 */
const CONFIG_DIR = process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
const CACHE = path.join(CONFIG_DIR, '.session-brief-cache.json');
/** Long enough that resume/compact/clear in one sitting are free, short enough to stay true. */
const TTL_MS = 3 * 60 * 1000;
/** A brief nobody waited for is worth more than a complete one. */
const STATUS_TIMEOUT_MS = 1500;
const MAX_LINES = 5;

/** Print nothing and get out of the way. */
function silent() {
  process.exit(0);
}

function emit(lines) {
  const text = lines.filter(Boolean).slice(0, MAX_LINES).join('\n');
  if (!text) silent();
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'SessionStart',
      additionalContext: text,
    },
  }));
  process.exit(0);
}

// ── .git on disk ─────────────────────────────────────────────────────────────

/** Walk up from `start` to the repo root and return its resolved .git directory. */
function findGitDir(start) {
  let dir = path.resolve(start);
  for (;;) {
    const candidate = path.join(dir, '.git');
    if (fs.existsSync(candidate)) {
      if (fs.statSync(candidate).isDirectory()) return { gitDir: candidate, root: dir };
      // A worktree or submodule: `.git` is a file containing `gitdir: <path>`.
      const pointer = fs.readFileSync(candidate, 'utf8').match(/^gitdir:\s*(.+)$/m);
      if (!pointer) return null;
      const resolved = path.resolve(dir, pointer[1].trim());
      return fs.existsSync(resolved) ? { gitDir: resolved, root: dir } : null;
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function readFile(...parts) {
  try {
    return fs.readFileSync(path.join(...parts), 'utf8');
  } catch {
    return null;
  }
}

/** The checked-out branch, or null when HEAD is detached. */
function currentBranch(gitDir) {
  const head = readFile(gitDir, 'HEAD');
  const m = head && head.match(/^ref:\s*refs\/heads\/(.+)$/m);
  return m ? m[1].trim() : null;
}

/** A ref's sha, from the loose ref or from packed-refs. */
function refSha(gitDir, ref) {
  const loose = readFile(gitDir, ...ref.split('/'));
  if (loose && /^[0-9a-f]{40}/.test(loose.trim())) return loose.trim().slice(0, 40);
  const packed = readFile(gitDir, 'packed-refs') ?? '';
  const m = packed.match(new RegExp(`^([0-9a-f]{40}) ${ref.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm'));
  return m ? m[1] : null;
}

/** HEAD's sha, whether HEAD is symbolic or detached. */
function headSha(gitDir, branch) {
  if (branch) return refSha(gitDir, `refs/heads/${branch}`);
  const head = (readFile(gitDir, 'HEAD') ?? '').trim();
  return /^[0-9a-f]{40}$/.test(head) ? head : null;
}

/**
 * The branch's upstream, from the repo config. Parsed by hand rather than through `git config`:
 * the file is a few hundred bytes and a subprocess is 100ms.
 */
function upstreamOf(gitDir, branch) {
  if (!branch) return null;
  const config = readFile(gitDir, 'config');
  if (!config) return null;
  const section = config.match(
    new RegExp(`\\[branch "${branch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"\\]([^[]*)`, 'm'),
  );
  if (!section) return null;
  const remote = section[1].match(/^\s*remote\s*=\s*(.+)$/m);
  const merge = section[1].match(/^\s*merge\s*=\s*refs\/heads\/(.+)$/m);
  if (!remote || !merge) return null;
  return `${remote[1].trim()}/${merge[1].trim()}`;
}

// ── The last commit, without running git ─────────────────────────────────────

/** `Add the order projection` from a loose commit object, plus its author timestamp. */
function commitFromObject(gitDir, sha) {
  try {
    const raw = zlib.inflateSync(
      fs.readFileSync(path.join(gitDir, 'objects', sha.slice(0, 2), sha.slice(2))),
    ).toString('utf8');
    const split = raw.indexOf('\n\n');
    if (split < 0) return null;
    const subject = raw.slice(split + 2).split('\n')[0].trim();
    const when = raw.slice(0, split).match(/^author .*? (\d{9,})\s[-+]\d{4}$/m);
    return subject ? { subject, at: when ? Number(when[1]) * 1000 : null } : null;
  } catch {
    // Packed away, or a repo without loose objects: the reflog is the fallback.
    return null;
  }
}

/**
 * The reflog's last `commit:` entry for HEAD's sha. Reading it is the cheapest way to a subject
 * once the object has been packed — the message is written there in plain text.
 */
function commitFromReflog(gitDir, sha) {
  const log = readFile(gitDir, 'logs', 'HEAD');
  if (!log) return null;
  const lines = log.split('\n').filter(Boolean).reverse();
  for (const line of lines) {
    const m = line.match(/^([0-9a-f]{40}) ([0-9a-f]{40}) .*?\s(\d{9,})\s[-+]\d{4}\t(.*)$/);
    if (!m) continue;
    if (sha && m[2] !== sha) continue;
    const message = m[4];
    if (!/^(?:commit|merge|rebase|revert|am|cherry-pick)\b/.test(message)) continue;
    const subject = message.replace(/^[^:]*:\s*/, '').trim();
    return subject ? { subject, at: Number(m[3]) * 1000 } : null;
  }
  return null;
}

// ── The two facts that need the index ────────────────────────────────────────

/**
 * One `git status`, bounded. `--porcelain=v2 --branch` answers both questions in a single call:
 * how many paths differ from HEAD, and how far the upstream has diverged.
 */
function statusOf(root) {
  try {
    const result = spawnSync(
      'git',
      ['status', '--porcelain=v2', '--branch', '--untracked-files=normal'],
      { cwd: root, encoding: 'utf8', timeout: STATUS_TIMEOUT_MS, windowsHide: true },
    );
    if (result.status !== 0 || typeof result.stdout !== 'string') return null;
    const lines = result.stdout.split('\n').filter(Boolean);
    const ab = result.stdout.match(/^# branch\.ab \+(\d+) -(\d+)$/m);
    return {
      dirty: lines.filter((l) => !l.startsWith('#')).length,
      ahead: ab ? Number(ab[1]) : null,
      behind: ab ? Number(ab[2]) : null,
    };
  } catch {
    return null;
  }
}

// ── Formatting ───────────────────────────────────────────────────────────────

function ago(at) {
  if (!at) return null;
  const minutes = Math.round((Date.now() - at) / 60000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  return `${days}d ago`;
}

/**
 * The work item a branch is for. The convention puts the id in the branch name
 * (`feature/4211-order-list`, `fix/AB#4211`), which is the only place it can be read without a
 * network call.
 */
function workItemOf(branch) {
  if (!branch) return null;
  const m = branch.match(/(?:^|[/_-])(?:ab#|#)?(\d{2,7})(?=$|[/_-])/i);
  return m ? m[1] : null;
}

function buildLines(found, cached) {
  const { gitDir, root } = found;

  const branch = currentBranch(gitDir);
  const sha = headSha(gitDir, branch);
  const status = statusOf(root);
  const lines = [];

  // 1. Where you are, and whether there is uncommitted work.
  if (branch || sha) {
    const where = branch ? `branch ${branch}` : `detached HEAD at ${sha.slice(0, 7)}`;
    const dirt = status === null
      ? null
      : status.dirty === 0 ? 'clean' : `${status.dirty} uncommitted change${status.dirty === 1 ? '' : 's'}`;
    lines.push(dirt ? `${where} · ${dirt}` : where);
  }

  // 2. What you last committed.
  if (sha) {
    const commit = commitFromObject(gitDir, sha) ?? commitFromReflog(gitDir, sha);
    if (commit) {
      const when = ago(commit.at);
      lines.push(`last ${sha.slice(0, 7)} ${commit.subject}${when ? ` (${when})` : ''}`);
    }
  }

  // 3. How you stand against the upstream.
  const upstream = upstreamOf(gitDir, branch);
  if (upstream) {
    const drift = [];
    if (status && status.ahead) drift.push(`ahead ${status.ahead}`);
    if (status && status.behind) drift.push(`behind ${status.behind}`);
    if (drift.length) lines.push(`${upstream} · ${drift.join(', ')}`);
    else if (status) lines.push(`${upstream} · in step`);
    else lines.push(upstream);
  } else if (branch) {
    // Deliberately not "never pushed": a branch can exist on the remote with no tracking set.
    lines.push('no upstream configured — a push needs an explicit remote and branch');
  }

  // 4. An open PR, only if something that can afford the lookup left it in the cache.
  if (cached?.pr?.number) {
    const title = cached.pr.title ? ` ${cached.pr.title}` : '';
    lines.push(`open PR !${cached.pr.number}${title}`);
  }

  // 5. What this branch is for.
  const item = workItemOf(branch);
  if (item) lines.push(`work item #${item} (from the branch name)`);

  return lines;
}

// ── Cache ────────────────────────────────────────────────────────────────────

function readCache() {
  try {
    return JSON.parse(fs.readFileSync(CACHE, 'utf8'));
  } catch {
    return {};
  }
}

function writeCache(cache) {
  try {
    fs.mkdirSync(path.dirname(CACHE), { recursive: true });
    fs.writeFileSync(CACHE, JSON.stringify(cache));
  } catch {
    /* best-effort: a cache write failure must not cost the brief */
  }
}

try {
  const raw = fs.readFileSync(0, 'utf8');
  const payload = raw.trim() ? JSON.parse(raw) : {};
  const cwd = payload.cwd || process.cwd();

  const found = findGitDir(cwd);
  if (!found) silent();                       // outside a repository there is nothing to orient

  const cache = readCache();
  const key = found.gitDir;
  const entry = cache[key];

  if (entry && Date.now() - entry.at < TTL_MS && Array.isArray(entry.lines)) {
    emit(entry.lines);
  }

  const lines = buildLines(found, entry);
  cache[key] = { at: Date.now(), lines, pr: entry?.pr ?? null };
  writeCache(cache);
  emit(lines);
} catch {
  // A bug in the hook must never be the first thing a session sees.
  silent();
}
