/**
 * SessionStart hook: which working days have activity but no hours on the board.
 *
 * The failure this closes is the only one `/worklog` cannot close by itself: it is a command, and a
 * command that is never typed logs nothing. Hours are forgotten silently — nothing on the board is
 * missing, nothing errors, the day simply never gets registered, and by the time the month is
 * invoiced the transcripts that could reconstruct it are gone.
 *
 * So the reminder has to come from outside the command, and it has to be cheap enough to run at
 * every session start:
 *
 *   1. `~/.claude/history.jsonl` is the input, not the transcripts. One line per prompt, each with
 *      a millisecond timestamp and the project path it was typed in — the set of days that had
 *      work, and where, in a single read of about a megabyte. Scanning ~/.claude/projects would
 *      mean streaming tens of megabytes of jsonl for the same answer.
 *   2. `~/.claude/worklog/pushed.json` — /worklog's own audit — says which periods already reached
 *      the board. A day covered by any entry is done; that is the same record the skill consults
 *      for its delta, so the two can never disagree.
 *   3. Only work under a mapped workspace root counts. A day spent entirely in ~/.claude is
 *      tooling: real, but not billable to anyone, and flagging it would train the reminder away.
 *   4. Weekends and today are never pending — today is still being worked.
 *
 * The result is cached in ~/.claude/.worklog-pending.json so statusline.js can render the same
 * count without re-reading anything, and so the badge clears itself: the cache is keyed on the
 * audit's mtime, so the moment /worklog writes an entry the snapshot is stale and the badge goes.
 *
 * Always exits 0, and prints nothing at all rather than an error.
 *
 * Generated by Claude Code at the user's request.
 */

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const CONFIG_DIR = process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
const HISTORY = path.join(CONFIG_DIR, 'history.jsonl');
const AUDIT = path.join(CONFIG_DIR, 'worklog', 'pushed.json');
const CACHE = path.join(CONFIG_DIR, '.worklog-pending.json');

/**
 * How far back a day is still worth chasing — the user's rule, not a duration: the current month,
 * or the current week when the week reaches back into the previous one. A day older than both is
 * water under the bridge and saying so would be nagging, not reminding.
 *
 * Concretely the cutoff is the earlier of the two starts, because either condition keeps a day:
 * on Wednesday 3 September the week began on 31 August, so 31 August is still in scope; on
 * Wednesday 17 September the month wins and the whole of September is.
 *
 * The window can reach 30 days at the end of a long month, which is exactly `cleanupPeriodDays`:
 * a day at the very start of such a month may already have lost its transcripts, and /worklog will
 * say so rather than invent hours. Closing it at zero is then the honest move.
 */
function cutoff() {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const weekStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() + 6) % 7));   // back to Monday
  return Math.min(monthStart.getTime(), weekStart.getTime());
}
/**
 * Only these roots hold work that anyone bills; everything else is tooling. They are machine paths,
 * so they come from the environment (`;`-separated, set by install.ps1), never from this file.
 * Unset means no root is mapped and nothing is ever pending — silence, not a false alarm.
 */
const WORKSPACE_ROOTS = listEnv('CLAUDE_WORKSPACE_ROOTS')
  .map((r) => r.replace(/\//g, '\\').replace(/\\?$/, '\\'));
/**
 * Folders directly under a root whose project is the subfolder below them, as in the CLAUDE.md
 * mapping — for those the label carries both levels (`<clients-root>/acme`), for the rest one.
 */
const NESTED = new Set(listEnv('CLAUDE_WORKSPACE_NESTED'));
/** A day whose whole activity is a couple of prompts is a check-in, not a working day. */
const MIN_PROMPTS = 3;
/** Naming the days is the point; past this many the line stops being readable. */
const MAX_LISTED = 4;

function listEnv(name) {
  return String(process.env[name] || '').split(';').map((s) => s.trim().toLowerCase()).filter(Boolean);
}

function silent() {
  process.exit(0);
}

/** Local calendar day of an epoch in ms, as yyyy-MM-dd — the format the audit and /worklog use. */
function dayOf(ms) {
  const d = new Date(ms);
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function isWeekend(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  const wd = new Date(y, m - 1, d).getDay();
  return wd === 0 || wd === 6;
}

/** The workspace folder a prompt belongs to — `<product-root>`, `<clients-root>/acme` — for the label. */
function workspaceOf(project) {
  const p = String(project || '').toLowerCase();
  const root = WORKSPACE_ROOTS.find((r) => p.startsWith(r));
  if (!root) return null;
  const rest = String(project).slice(root.length).split(/[\\/]/).filter(Boolean);
  if (!rest.length) return null;
  return NESTED.has(rest[0].toLowerCase()) && rest[1] ? `${rest[0]}/${rest[1]}` : rest[0];
}

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

/** Days already on the board: any audit entry whose period covers them, zero hours included. */
function auditedDays() {
  const raw = readJson(AUDIT);
  // The file has been a bare array since the first run; tolerate the { entries: [] } shape too
  // rather than silently reporting every day as pending if it ever changes.
  const entries = Array.isArray(raw) ? raw : (raw && Array.isArray(raw.entries) ? raw.entries : []);
  const covered = new Set();
  for (const e of entries) {
    const from = e.periodFrom || e.period;
    const to = e.periodTo || e.periodFrom || e.period;
    if (!from) continue;
    for (let ms = Date.parse(`${from}T12:00:00`); ms <= Date.parse(`${to}T12:00:00`); ms += 864e5) {
      covered.add(dayOf(ms));
    }
  }
  return covered;
}

/** yyyy-MM-dd → { prompts, workspaces:Set }, for the loggable prompts inside the lookback. */
function activeDays(since) {
  let text;
  try {
    text = fs.readFileSync(HISTORY, 'utf8');
  } catch {
    return new Map();
  }
  const days = new Map();
  for (const line of text.split('\n')) {
    if (!line) continue;
    let rec;
    try {
      rec = JSON.parse(line);
    } catch {
      continue;
    }
    if (!rec || typeof rec.timestamp !== 'number' || rec.timestamp < since) continue;
    const ws = workspaceOf(rec.project);
    if (!ws) continue;
    const day = dayOf(rec.timestamp);
    let d = days.get(day);
    if (!d) days.set(day, (d = { prompts: 0, workspaces: new Set() }));
    d.prompts += 1;
    d.workspaces.add(ws);
  }
  return days;
}

function compute() {
  const today = dayOf(Date.now());
  const since = cutoff();
  const covered = auditedDays();
  const pending = [];
  for (const [day, d] of activeDays(since)) {
    if (day >= today || isWeekend(day) || covered.has(day) || d.prompts < MIN_PROMPTS) continue;
    pending.push({ date: day, prompts: d.prompts, workspaces: [...d.workspaces].sort() });
  }
  pending.sort((a, b) => a.date.localeCompare(b.date));
  return { day: today, auditMtime: mtime(AUDIT), pending, ts: Date.now() };
}

function mtime(file) {
  try {
    return fs.statSync(file).mtimeMs;
  } catch {
    return 0;
  }
}

function save(snapshot) {
  try {
    fs.writeFileSync(CACHE, JSON.stringify(snapshot), 'utf8');
  } catch {
    /* a cache that cannot be written costs a recomputation, never a failure */
  }
}

/**
 * A day's workspaces, short enough to read: a nested root alone is dropped once `<root>/<project>` is
 * there — same root, and the mapping says the project is the subfolder — and the tail becomes a
 * count. The line orients; /worklog is what enumerates.
 */
function label(workspaces) {
  const ws = workspaces.filter((w) => !workspaces.some((o) => o !== w && o.startsWith(`${w}/`)));
  return ws.length > 2 ? `${ws.slice(0, 2).join(', ')} +${ws.length - 2}` : ws.join(', ');
}

/** One line, naming the days and where they were spent, because a bare count invites postponing. */
function line(pending) {
  const shown = pending.slice(0, MAX_LISTED)
    .map((p) => `${p.date} (${label(p.workspaces)})`)
    .join(', ');
  const rest = pending.length > MAX_LISTED ? `, +${pending.length - MAX_LISTED} altri` : '';
  return `⏱ Ore non registrate su ${pending.length} giorn${pending.length === 1 ? 'o' : 'i'}: `
    + `${shown}${rest} — chiudili con /worklog <data>.`;
}

const snapshot = compute();
save(snapshot);
if (!snapshot.pending.length) silent();

process.stdout.write(JSON.stringify({
  hookSpecificOutput: {
    hookEventName: 'SessionStart',
    additionalContext: line(snapshot.pending),
  },
}));
process.exit(0);
