#!/usr/bin/env node
/**
 * Tests for hooks/format-on-edit.ps1. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * The hook is the one PowerShell script in the set, but the test is Node like the others, so
 * the one command above stays enough to check every hook.
 *
 * The whole file runs the hook with `-DryRun`, which prints the formatter invocation instead of
 * performing it. That is the only way to assert the routing on any machine: the real run needs the
 * .NET SDK, an installed node_modules tree, or both, and a test that formats real files would
 * rewrite them. So every case fabricates a project layout in a temp directory and asserts *which*
 * formatter the hook chose — and, far more often, that it chose none.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'format-on-edit.ps1');
const created = [];

/** pwsh is the kit's shell, but a machine without it must not fail the suite. */
const PWSH = ['pwsh', 'powershell'].find(
  (exe) => spawnSync(exe, ['-NoProfile', '-Command', 'exit 0'], { encoding: 'utf8' }).status === 0,
);

process.on('exit', () => {
  for (const root of created) {
    try { rmSync(root, { recursive: true, force: true }); } catch { /* tmp, let the OS have it */ }
  }
});

/**
 * Build a project layout under a temp root. `files` maps a relative path to its content;
 * a path ending in `/` creates a directory. Returns the absolute root.
 */
function fixture(files) {
  const root = mkdtempSync(join(tmpdir(), 'fmt-'));
  created.push(root);
  for (const [rel, content] of Object.entries(files)) {
    const full = join(root, rel);
    if (rel.endsWith('/')) { mkdirSync(full, { recursive: true }); continue; }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
  }
  return root;
}

/** Run the hook in dry-run mode and return what it decided to invoke ('' = nothing). */
function run(payload) {
  const input = typeof payload === 'string' ? payload : JSON.stringify(payload);
  const result = spawnSync(
    PWSH,
    ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', HOOK, '-DryRun'],
    { input, encoding: 'utf8' },
  );
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  return result.stdout.trim();
}

const onFile = (file_path) => run({ tool_name: 'Write', tool_input: { file_path } });

test('a C# file in a project that configures a style is formatted with the .NET formatter', { skip: !PWSH }, () => {
  const root = fixture({
    '.editorconfig': '[*.cs]\nindent_size = 4\n',
    'src/App/App.csproj': '<Project Sdk="Microsoft.NET.Sdk" />',
    'src/App/Orders/OrderService.cs': 'class OrderService { }',
  });
  const plan = onFile(join(root, 'src/App/Orders/OrderService.cs'));
  assert.match(plan, /^dotnet format whitespace /);
  assert.match(plan, /App\.csproj/, 'the nearest project scopes the run');
  assert.match(plan, /--include .*OrderService\.cs/, 'only the file just touched');
  assert.match(plan, /--no-restore/, 'a hook must never restore packages mid-session');
});

test('a web file in a project that configures a formatter goes through the local package runner', { skip: !PWSH }, () => {
  const root = fixture({
    'package.json': '{ "name": "web", "devDependencies": {} }',
    '.prettierrc': '{ "singleQuote": true }',
    'node_modules/': '',
    'src/app/order-list.component.ts': 'export class OrderList {}',
  });
  const plan = onFile(join(root, 'src/app/order-list.component.ts'));
  assert.match(plan, /^npx --no-install prettier --write /);
  assert.match(plan, /order-list\.component\.ts/);
});

test('the formatter key may live in the package manifest instead of its own file', { skip: !PWSH }, () => {
  const root = fixture({
    'package.json': '{ "name": "web", "prettier": { "printWidth": 100 } }',
    'node_modules/': '',
    'src/main.tsx': 'export default function App() { return null; }',
  });
  assert.match(onFile(join(root, 'src/main.tsx')), /^npx --no-install prettier/);
});

// ── Doing nothing is the common case, and the one that must never surprise ─────────────────────

test('a file outside any project is left alone', { skip: !PWSH }, () => {
  const root = fixture({ 'scratch/Notes.cs': 'class Notes { }', 'scratch/script.ts': 'export {};' });
  assert.equal(onFile(join(root, 'scratch/Notes.cs')), '');
  assert.equal(onFile(join(root, 'scratch/script.ts')), '');
});

test('a project with no style configured is left alone', { skip: !PWSH }, () => {
  // A .csproj but no .editorconfig: the project never chose a style, so there is none to apply.
  const noStyle = fixture({
    'src/App/App.csproj': '<Project Sdk="Microsoft.NET.Sdk" />',
    'src/App/Program.cs': 'class Program { }',
  });
  assert.equal(onFile(join(noStyle, 'src/App/Program.cs')), '');

  // A package.json but no formatter configured anywhere.
  const noFormatter = fixture({
    'package.json': '{ "name": "web" }',
    'node_modules/': '',
    'src/main.ts': 'export {};',
  });
  assert.equal(onFile(join(noFormatter, 'src/main.ts')), '');
});

test('a project whose dependencies are not installed is left alone', { skip: !PWSH }, () => {
  // Without node_modules the local runner would have to fetch the formatter: never, mid-session.
  const root = fixture({
    'package.json': '{ "name": "web" }',
    '.prettierrc': '{}',
    'src/main.ts': 'export {};',
  });
  assert.equal(onFile(join(root, 'src/main.ts')), '');
});

test('generated and dependency trees are never formatted', { skip: !PWSH }, () => {
  const root = fixture({
    'package.json': '{ "name": "web" }',
    '.prettierrc': '{}',
    'node_modules/left-pad/index.js': 'module.exports = 1;',
    'src/App/App.csproj': '<Project Sdk="Microsoft.NET.Sdk" />',
    '.editorconfig': '[*.cs]\nindent_size = 4\n',
    'src/App/obj/Debug/App.AssemblyInfo.cs': '// generated',
  });
  assert.equal(onFile(join(root, 'node_modules/left-pad/index.js')), '');
  assert.equal(onFile(join(root, 'src/App/obj/Debug/App.AssemblyInfo.cs')), '');
});

test('an extension with no formatter of its own is left alone', { skip: !PWSH }, () => {
  const root = fixture({
    '.editorconfig': 'root = true\n',
    'package.json': '{ "name": "web" }',
    '.prettierrc': '{}',
    'node_modules/': '',
    'notes.txt': 'hello',
    'data.csv': 'a,b',
    'query.sql': 'SELECT 1',
  });
  for (const rel of ['notes.txt', 'data.csv', 'query.sql']) {
    assert.equal(onFile(join(root, rel)), '', rel);
  }
});

test('anything unusable is a no-op rather than a failed tool call', { skip: !PWSH }, () => {
  assert.equal(run(''), '');
  assert.equal(run('not json at all'), '');
  assert.equal(run('{}'), '');
  assert.equal(run({ tool_input: {} }), '');
  assert.equal(run({ tool_input: { file_path: '' } }), '');
  assert.equal(onFile(join(tmpdir(), 'does-not-exist-format-hook', 'Program.cs')), '');
  assert.equal(onFile(tmpdir()), '', 'a directory is not a file to format');
});
