#!/usr/bin/env node
/**
 * Tests for hooks/guard-destructive.js. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * The hook does no I/O at all, so there is nothing to fake: every case is a command line in and a
 * decision out. Half of the file is deliberately about the *false* positives — a guard that fires
 * on `grep "DROP TABLE"` teaches the user to approve without reading, which is worse than no guard.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'guard-destructive.js');

/** Run the hook on raw stdin and return its decision. */
function runRaw(input) {
  const result = spawnSync(process.execPath, [HOOK], { input, encoding: 'utf8' });
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  if (!result.stdout.trim()) return { decision: 'approve', reason: '' };
  const { hookSpecificOutput: out } = JSON.parse(result.stdout);
  assert.equal(out.hookEventName, 'PreToolUse');
  return { decision: out.permissionDecision, reason: out.permissionDecisionReason };
}

const run = (command) => runRaw(JSON.stringify({ tool_input: { command }, cwd: process.cwd() }));

/** Every asked case must carry a reason, or the prompt tells the user nothing. */
function asks(command, reasonPattern) {
  const { decision, reason } = run(command);
  assert.equal(decision, 'ask', command);
  assert.match(reason, /Confirm\?$/, command);
  if (reasonPattern) assert.match(reason, reasonPattern, command);
}

const approves = (command) => assert.equal(run(command).decision, 'approve', command);

// ── True positives, all of them buried where a permission prefix cannot see them ──────────────

test('dropping a database, schema or table', () => {
  asks('docker exec -i sqlserver /opt/mssql-tools/bin/sqlcmd -U sa -Q "DROP DATABASE Sales"', /drops a database/);
  asks('sqlcmd -S localhost -Q "drop table dbo.Orders"');
  asks('docker compose exec -T db psql -U postgres -c "DROP SCHEMA public CASCADE"');
  asks('sqlcmd -Q "IF EXISTS (SELECT 1 FROM sys.tables) DROP TABLE dbo.Tmp"');
  asks('docker exec pg dropdb --if-exists sales', /through the database CLI/);
});

test('truncating a table', () => {
  asks('sqlcmd -Q "TRUNCATE TABLE dbo.AuditLog"', /truncates a table/);
  asks('docker exec pg psql -U postgres -d sales -c "truncate orders"');
});

test('the migration tool dropping or unwinding the model', () => {
  asks('dotnet ef database drop --force --project src/App.Data', /migration tool dropping/);
  asks('dotnet ef migrations remove --project src/App.Data', /deletes the last migration/);
  asks('dotnet-ef database drop -f');
});

test('flushing a cache', () => {
  asks('docker exec -it redis redis-cli FLUSHALL', /EVERY key in EVERY database/);
  asks('redis-cli -h localhost -n 3 flushdb', /the selected cache database/);
  asks('docker exec memcached bash -c "echo flush_all | nc localhost 11211"');
});

test('tearing containers down with their volumes', () => {
  asks('docker compose down -v', /WITH its volumes/);
  asks('docker compose -f docker-compose.dev.yml down --volumes --remove-orphans');
  asks('docker-compose down -v --rmi local');
});

test('pruning containers and deleting volumes', () => {
  asks('docker system prune -a --volumes -f', /prunes container resources/);
  asks('docker builder prune');
  asks('docker volume rm app_sqlserver_data', /deletes a container volume/);
  asks('podman volume prune -f');
});

test('purging or deleting a broker queue', () => {
  asks('docker exec rabbit rabbitmqctl purge_queue orders.dlq', /broker queue/);
  asks('docker exec rabbit rabbitmqadmin delete queue name=orders');
  asks('az servicebus queue delete --namespace-name bus --resource-group rg --name orders');
});

test('deleting a cloud, Azure DevOps or Kubernetes resource', () => {
  asks('az group delete --name rg-dev --yes --no-wait', /cloud or Azure DevOps resource/);
  asks('az boards work-item delete --id 4211 --yes');
  asks('kubectl delete deployment api -n staging', /Kubernetes resource/);
  asks('kubectl -n staging delete pvc data-api-0');
  asks('helm uninstall api -n staging', /Helm release/);
  asks('terraform destroy -auto-approve', /Terraform state/);
  asks('aws s3api delete-bucket --bucket app-artifacts');
  asks('gh repo delete owner/name --yes', /on the remote host/);
});

test('force-deleting a git branch', () => {
  asks('git branch -D feature/spike', /force-deletes a branch/);
  asks('git branch --delete --force feature/spike');
  asks('git branch -Dr origin/feature/spike');
});

test('the danger is found inside a pipeline, not only at the head of the line', () => {
  asks('dotnet build && docker compose down -v && docker compose up -d');
  asks('echo "cleaning" ; docker exec -i db sqlcmd -Q "DROP TABLE dbo.T"');
  asks('docker exec -i db sqlcmd -Q "DROP TABLE dbo.T" | tee drop.log');
});

// ── False positives: the half that decides whether the guard is worth having ──────────────────

test('a searcher hunting for the danger is not the danger', () => {
  approves('grep -rn "DROP TABLE" ./src');
  approves('rg -i "drop database" --glob "*.sql"');
  approves('findstr /S /I "TRUNCATE TABLE" *.sql');
  approves('Select-String -Path .\\migrations\\*.sql -Pattern "DROP SCHEMA"');
  approves('git grep -n "flushall"');
  approves('git log --oneline --grep="drop table"');
  approves('git log -p -- src/Migrations');
});

test('a comment is not an instruction', () => {
  approves('dotnet build # then dotnet ef database drop, once the backup is taken');
  approves('docker compose up -d   # remember: docker compose down -v wipes the volumes');
  approves('sqlcmd -Q "-- DROP TABLE dbo.Orders was reverted"');
  approves('sqlcmd -Q "/* DROP DATABASE Sales */ SELECT 1"');
});

test('a file path that merely contains the word is not a statement', () => {
  approves('psql -U postgres -f scripts/drop-old-tables.sql');
  approves('code src/Migrations/20240101_DropTable.cs');
  approves('cat ./scripts/database-drop.ps1');
  approves('sqlcmd -i migrations/truncate-staging.sql');
  approves('git add tools/prune-artifacts.js');
});

test('a dry run, a what-if or a help page changes nothing', () => {
  approves('dotnet ef database drop --dry-run');
  approves('kubectl delete deployment api --dry-run=client -o yaml');
  approves('docker system prune --help');
  approves('az group delete --name rg-dev --what-if');
  approves('Remove-AzResourceGroup -Name rg-dev -WhatIf');
  approves('dotnet ef migrations remove --help');
});

test('a SELECT that merely mentions the word is read-only', () => {
  approves('sqlcmd -Q "SELECT name FROM sys.tables WHERE name = \'DropLog\'"');
  approves('sqlcmd -Q "SELECT \'DROP TABLE \' + name FROM sys.tables"');
  approves('docker exec pg psql -c "select * from pg_stat_activity where query like \'%truncate%\'"');
  approves('sqlcmd -Q "SHOW TABLES"');
});

test('a generated statement is still caught once the read-only part is stripped', () => {
  // The regression the SELECT rule could have caused: blanking too much.
  asks('sqlcmd -Q "SELECT 1; DROP TABLE dbo.Tmp"');
});

test('the everyday commands stay silent', () => {
  const quiet = [
    'dotnet build',
    'dotnet test --no-build',
    'npm run build',
    'npm uninstall lodash',
    'docker compose up -d',
    'docker compose down',
    'docker compose restart api',
    'docker ps -a',
    'git branch -d feature/merged',
    'git branch --delete feature/merged',
    'git push origin feature/x',
    'git status',
    'az pipelines runs list --top 5',
    'az repos pr list --status active',
    'kubectl get pods -n staging',
    'kubectl logs deployment/api',
    'redis-cli GET user:1',
    'ls -la',
    'Get-ChildItem -Recurse',
  ];
  for (const command of quiet) approves(command);
});

test('anything unusable is approved rather than blocking the work', () => {
  assert.equal(runRaw('').decision, 'approve');
  assert.equal(runRaw('not json at all').decision, 'approve');
  assert.equal(runRaw('{}').decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: {} })).decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: { command: '   ' } })).decision, 'approve');
});
