#!/usr/bin/env node
/**
 * Tests for hooks/guard-shell.js — the one PreToolUse entry point for Bash / PowerShell, running
 * the default-branch check (hooks/lib/default-branch.js) and the destructive-action check
 * (hooks/lib/destructive.js). Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * Default-branch cases: the check deliberately never runs `git`, it reads HEAD and the refs
 * straight out of `.git`. So the fixtures fabricate that directory rather than creating real
 * repositories — hermetic, and fast enough to keep in CI. Most cases are regressions: detection
 * used to scan the whole command line, which was both too lax (a dry run chained before a real
 * push read as a dry run) and too eager (`git log --grep=commit` read as a commit).
 *
 * Destructive cases: pure text in, decision out. Half of them are deliberately about the *false*
 * positives — a guard that fires on `grep "DROP TABLE"` teaches the user to approve without
 * reading, which is worse than no guard. They run from a working-branch fixture, so the
 * default-branch check can never be what answers.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'guard-shell.js');
const SHA = '0'.repeat(40);
const created = [];

/** A repo checked out on `current`, whose origin/HEAD names `defaultBranch`. */
function fixture(current, defaultBranch = 'main') {
  const root = mkdtempSync(join(tmpdir(), 'guard-'));
  created.push(root);
  const gitDir = join(root, '.git');
  mkdirSync(join(gitDir, 'refs', 'remotes', 'origin'), { recursive: true });
  writeFileSync(join(gitDir, 'HEAD'), `ref: refs/heads/${current}\n`);
  writeFileSync(
    join(gitDir, 'refs', 'remotes', 'origin', 'HEAD'),
    `ref: refs/remotes/origin/${defaultBranch}\n`,
  );
  for (const branch of new Set([current, defaultBranch])) {
    const ref = join(gitDir, 'refs', 'heads', branch);
    mkdirSync(dirname(ref), { recursive: true }); // `feature/x` is a nested path
    writeFileSync(ref, `${SHA}\n`);
  }
  return root;
}

process.on('exit', () => {
  for (const root of created) {
    try { rmSync(root, { recursive: true, force: true }); } catch { /* tmp, let the OS have it */ }
  }
});

/** Run the hook on raw stdin and return its decision. */
function runRaw(input) {
  const result = spawnSync(process.execPath, [HOOK], { input, encoding: 'utf8' });
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  if (!result.stdout.trim()) return { decision: 'approve', reason: '' };
  const { hookSpecificOutput: out } = JSON.parse(result.stdout);
  assert.equal(out.hookEventName, 'PreToolUse');
  return { decision: out.permissionDecision, reason: out.permissionDecisionReason };
}

const run = (command, cwd) => runRaw(JSON.stringify({ tool_input: { command }, cwd }));

const onDefault = fixture('main');
const onFeature = fixture('feature/x');

test('on the default branch, a commit or a push asks for confirmation', () => {
  for (const command of ['git commit -m "wip"', 'git push', 'git commit -am "wip" && git push']) {
    const { decision, reason } = run(command, onDefault);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /default branch/, command);
  }
});

test('the action in the reason names what the command actually does', () => {
  assert.match(run('git commit -m "wip"', onDefault).reason, /direct commit here/);
  assert.match(run('git push origin main', onDefault).reason, /direct push here/);
  assert.match(run('git commit -m "wip" && git push', onDefault).reason, /direct commit and push here/);
});

test('a command that only mentions a verb is not a commit or a push', () => {
  // Regression: `git\b[^;&|]*\bcommit\b` matched the word anywhere after `git`, so read-only
  // commands prompted on the default branch.
  const readOnly = [
    'git log --grep=commit',
    'git config --global push.default simple',
    'git show --stat HEAD',
    'git log --oneline origin/main..HEAD',
    'ls -la',
    'echo push',
  ];
  for (const command of readOnly) {
    assert.equal(run(command, onDefault).decision, 'approve', command);
  }
});

test('a dry run changes nothing, so it is approved', () => {
  assert.equal(run('git push --dry-run', onDefault).decision, 'approve');
  assert.equal(run('git push --dry-run origin main', onFeature).decision, 'approve');
  assert.equal(run('git push -n origin main', onFeature).decision, 'approve');
  assert.equal(run('git push origin main --dry-run', onFeature).decision, 'approve');
});

test('a dry run does not cover a real push chained after it', () => {
  // Regression: `--dry-run` was tested against the whole line, so this whole call was approved.
  for (const command of [
    'git push --dry-run origin main && git push origin main',
    'git push --dry-run origin main; git push origin main',
    'git push --dry-run origin main | tee log.txt && git push origin main',
  ]) {
    assert.equal(run(command, onFeature).decision, 'ask', command);
  }
  // A bare `git push` reaches the default branch only from the default branch itself.
  for (const command of ['git push --dry-run && git push', 'git push --dry-run && git commit -m "wip"']) {
    assert.equal(run(command, onDefault).decision, 'ask', command);
  }
  assert.equal(run('git push --dry-run && git push', onFeature).decision, 'approve');
});

test('`-n` means --no-verify on a commit, not a dry run', () => {
  assert.equal(run('git commit -n -m "wip"', onDefault).decision, 'ask');
});

test('from a working branch, only a push that reaches the default branch asks', () => {
  const reaches = [
    'git push origin main',
    'git push -u origin main',
    'git push origin HEAD:main',
    'git push origin HEAD:refs/heads/main',
    'git push origin +main',
    'git push --set-upstream origin main',
    'git push --force-with-lease origin main',
  ];
  for (const command of reaches) {
    const { decision, reason } = run(command, onFeature);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /pushes to 'main'/, command);
  }

  const stays = [
    'git push',
    'git push -u origin feature/x',
    'git push origin feature/main-cleanup', // the name must be a whole ref part
    'git push origin main-line',
    'git commit -m "wip"',
    'git commit -m "push to main"', // the message is not a ref
    'git commit --amend --no-edit',
  ];
  for (const command of stays) {
    assert.equal(run(command, onFeature).decision, 'approve', command);
  }
});

test('a push of every ref asks, because no name matching can clear it', () => {
  // Regression: `--all` / `--mirror` never name the branch, so the token match could not see them.
  for (const command of ['git push --all origin', 'git push --mirror origin', 'git push --all']) {
    const { decision, reason } = run(command, onFeature);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /every ref/, command);
  }
});

test('global options are skipped when reading the subcommand', () => {
  // The author's own push command: quoted values with spaces, two `-c` pairs before the verb.
  const real = "git -c credential.helper= -c credential.helper='!gh auth git-credential' push -u origin feature/x";
  assert.equal(run(real, onFeature).decision, 'approve');
  assert.equal(run(real.replace('feature/x', 'main'), onFeature).decision, 'ask');
  assert.equal(run('git --no-pager push origin main', onFeature).decision, 'ask');
  assert.equal(run('git.exe push origin main', onFeature).decision, 'ask');
});

test('`git -C` picks the repo the command really acts on', () => {
  // cwd sits on the default branch, `-C` points at the working-branch repo: no direct-commit prompt.
  assert.equal(run(`git -C ${onFeature} commit -m "wip"`, onDefault).decision, 'approve');
  // And the other way round.
  assert.match(run(`git -C ${onDefault} commit -m "wip"`, onFeature).reason, /default branch/);
});

test('a repo whose default branch is not main is handled by name', () => {
  const trunk = fixture('feature/y', 'release/v1');
  assert.match(run('git push origin release/v1', trunk).reason, /pushes to 'release\/v1'/);
  assert.equal(run('git push origin release/v2', trunk).decision, 'approve');
});

test('anything unusable is approved rather than blocking the work', () => {
  assert.equal(runRaw('').decision, 'approve');
  assert.equal(runRaw('not json at all').decision, 'approve');
  assert.equal(runRaw('{}').decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: {} })).decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: { command: '   ' } })).decision, 'approve');
  assert.equal(run('git commit -m "wip"', join(tmpdir(), 'does-not-exist-guard')).decision, 'approve');
  assert.equal(run('git commit -m "wip"', tmpdir()).decision, 'approve'); // outside any repo
});

// ── Destructive actions ────────────────────────────────────────────────────────────────────────

/** A destructive-check case, run from a working branch so only that check can answer. */
const runShell = (command) => run(command, onFeature);

/** Every asked case must carry a reason, or the prompt tells the user nothing. */
function asks(command, reasonPattern) {
  const { decision, reason } = runShell(command);
  assert.equal(decision, 'ask', command);
  assert.match(reason, /Confirm\?$/, command);
  if (reasonPattern) assert.match(reason, reasonPattern, command);
}

const approves = (command) => assert.equal(runShell(command).decision, 'approve', command);

// ── True positives, all of them buried where a permission prefix cannot see them ──────────────

test('dropping a database, schema or table', () => {
  asks('docker exec -i sqlserver /opt/mssql-tools/bin/sqlcmd -U sa -Q "DROP DATABASE Sales"', /drops a database/);
  asks('sqlcmd -S localhost -Q "drop table dbo.Orders"');
  asks('docker compose exec -T db psql -U postgres -c "DROP SCHEMA public CASCADE"');
  asks('sqlcmd -Q "IF EXISTS (SELECT 1 FROM sys.tables) DROP TABLE dbo.Tmp"');
  asks('docker exec pg dropdb --if-exists sales', /through the database CLI/);
});

test('truncating a table', () => {
  asks('sqlcmd -Q "TRUNCATE TABLE dbo.AuditLog"', /truncates a table/);
  asks('docker exec pg psql -U postgres -d sales -c "truncate orders"');
});

test('the migration tool dropping or unwinding the model', () => {
  asks('dotnet ef database drop --force --project src/App.Data', /migration tool dropping/);
  asks('dotnet ef migrations remove --project src/App.Data', /deletes the last migration/);
  asks('dotnet-ef database drop -f');
});

test('flushing a cache', () => {
  asks('docker exec -it redis redis-cli FLUSHALL', /EVERY key in EVERY database/);
  asks('redis-cli -h localhost -n 3 flushdb', /the selected cache database/);
  asks('docker exec memcached bash -c "echo flush_all | nc localhost 11211"');
});

test('tearing containers down with their volumes', () => {
  asks('docker compose down -v', /WITH its volumes/);
  asks('docker compose -f docker-compose.dev.yml down --volumes --remove-orphans');
  asks('docker-compose down -v --rmi local');
});

test('pruning containers and deleting volumes', () => {
  asks('docker system prune -a --volumes -f', /prunes container resources/);
  asks('docker builder prune');
  asks('docker volume rm app_sqlserver_data', /deletes a container volume/);
  asks('podman volume prune -f');
});

test('purging or deleting a broker queue', () => {
  asks('docker exec rabbit rabbitmqctl purge_queue orders.dlq', /broker queue/);
  asks('docker exec rabbit rabbitmqadmin delete queue name=orders');
  asks('az servicebus queue delete --namespace-name bus --resource-group rg --name orders');
});

test('deleting a cloud, Azure DevOps or Kubernetes resource', () => {
  asks('az group delete --name rg-dev --yes --no-wait', /cloud or Azure DevOps resource/);
  asks('az boards work-item delete --id 4211 --yes');
  asks('kubectl delete deployment api -n staging', /Kubernetes resource/);
  asks('kubectl -n staging delete pvc data-api-0');
  asks('helm uninstall api -n staging', /Helm release/);
  asks('terraform destroy -auto-approve', /Terraform state/);
  asks('aws s3api delete-bucket --bucket app-artifacts');
  asks('gh repo delete owner/name --yes', /on the remote host/);
});

test('force-deleting a git branch', () => {
  asks('git branch -D feature/spike', /force-deletes a branch/);
  asks('git branch --delete --force feature/spike');
  asks('git branch -Dr origin/feature/spike');
});

test('the danger is found inside a pipeline, not only at the head of the line', () => {
  asks('dotnet build && docker compose down -v && docker compose up -d');
  asks('echo "cleaning" ; docker exec -i db sqlcmd -Q "DROP TABLE dbo.T"');
  asks('docker exec -i db sqlcmd -Q "DROP TABLE dbo.T" | tee drop.log');
});

// ── False positives: the half that decides whether the guard is worth having ──────────────────

test('a searcher hunting for the danger is not the danger', () => {
  approves('grep -rn "DROP TABLE" ./src');
  approves('rg -i "drop database" --glob "*.sql"');
  approves('findstr /S /I "TRUNCATE TABLE" *.sql');
  approves('Select-String -Path .\\migrations\\*.sql -Pattern "DROP SCHEMA"');
  approves('git grep -n "flushall"');
  approves('git log --oneline --grep="drop table"');
  approves('git log -p -- src/Migrations');
});

test('a comment is not an instruction', () => {
  approves('dotnet build # then dotnet ef database drop, once the backup is taken');
  approves('docker compose up -d   # remember: docker compose down -v wipes the volumes');
  approves('sqlcmd -Q "-- DROP TABLE dbo.Orders was reverted"');
  approves('sqlcmd -Q "/* DROP DATABASE Sales */ SELECT 1"');
});

test('a file path that merely contains the word is not a statement', () => {
  approves('psql -U postgres -f scripts/drop-old-tables.sql');
  approves('code src/Migrations/20240101_DropTable.cs');
  approves('cat ./scripts/database-drop.ps1');
  approves('sqlcmd -i migrations/truncate-staging.sql');
  approves('git add tools/prune-artifacts.js');
});

test('a dry run, a what-if or a help page changes nothing', () => {
  approves('dotnet ef database drop --dry-run');
  approves('kubectl delete deployment api --dry-run=client -o yaml');
  approves('docker system prune --help');
  approves('az group delete --name rg-dev --what-if');
  approves('Remove-AzResourceGroup -Name rg-dev -WhatIf');
  approves('dotnet ef migrations remove --help');
});

test('a SELECT that merely mentions the word is read-only', () => {
  approves('sqlcmd -Q "SELECT name FROM sys.tables WHERE name = \'DropLog\'"');
  approves('sqlcmd -Q "SELECT \'DROP TABLE \' + name FROM sys.tables"');
  approves('docker exec pg psql -c "select * from pg_stat_activity where query like \'%truncate%\'"');
  approves('sqlcmd -Q "SHOW TABLES"');
});

test('a generated statement is still caught once the read-only part is stripped', () => {
  // The regression the SELECT rule could have caused: blanking too much.
  asks('sqlcmd -Q "SELECT 1; DROP TABLE dbo.Tmp"');
});

test('the everyday commands stay silent', () => {
  const quiet = [
    'dotnet build',
    'dotnet test --no-build',
    'npm run build',
    'npm uninstall lodash',
    'docker compose up -d',
    'docker compose down',
    'docker compose restart api',
    'docker ps -a',
    'git branch -d feature/merged',
    'git branch --delete feature/merged',
    'git push origin feature/x',
    'git status',
    'az pipelines runs list --top 5',
    'az repos pr list --status active',
    'kubectl get pods -n staging',
    'kubectl logs deployment/api',
    'redis-cli GET user:1',
    'ls -la',
    'Get-ChildItem -Recurse',
  ];
  for (const command of quiet) approves(command);
});

// ── Both checks on one line ────────────────────────────────────────────────────────────────────

test('when both checks fire, one prompt carries both reasons', () => {
  const { decision, reason } = run('git push origin main && docker compose down -v', onFeature);
  assert.equal(decision, 'ask');
  assert.match(reason, /pushes to 'main'/);
  assert.match(reason, /WITH its volumes/);
});

test('a destructive action on the default branch is still caught', () => {
  const { decision, reason } = run('git branch -D feature/spike', onDefault);
  assert.equal(decision, 'ask');
  assert.match(reason, /force-deletes a branch/);
  assert.doesNotMatch(reason, /default branch/);
});
