#!/usr/bin/env node
/**
 * Tests for hooks/guard-default-branch.js. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test tools/
 *
 * The hook deliberately never runs `git`: it reads HEAD and the refs straight out of `.git`. So the
 * fixtures fabricate that directory rather than creating real repositories — hermetic, and fast
 * enough to keep in CI.
 *
 * Most cases here are regressions. Detection used to scan the whole command line, which was both
 * too lax (`git push --dry-run origin main && git push origin main` read as a dry run) and too
 * eager (`git log --grep=commit` read as a commit).
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'guard-default-branch.js');
const SHA = '0'.repeat(40);
const created = [];

/** A repo checked out on `current`, whose origin/HEAD names `defaultBranch`. */
function fixture(current, defaultBranch = 'main') {
  const root = mkdtempSync(join(tmpdir(), 'guard-'));
  created.push(root);
  const gitDir = join(root, '.git');
  mkdirSync(join(gitDir, 'refs', 'remotes', 'origin'), { recursive: true });
  writeFileSync(join(gitDir, 'HEAD'), `ref: refs/heads/${current}\n`);
  writeFileSync(
    join(gitDir, 'refs', 'remotes', 'origin', 'HEAD'),
    `ref: refs/remotes/origin/${defaultBranch}\n`,
  );
  for (const branch of new Set([current, defaultBranch])) {
    const ref = join(gitDir, 'refs', 'heads', branch);
    mkdirSync(dirname(ref), { recursive: true }); // `feature/x` is a nested path
    writeFileSync(ref, `${SHA}\n`);
  }
  return root;
}

process.on('exit', () => {
  for (const root of created) {
    try { rmSync(root, { recursive: true, force: true }); } catch { /* tmp, let the OS have it */ }
  }
});

/** Run the hook on raw stdin and return its decision. */
function runRaw(input) {
  const result = spawnSync(process.execPath, [HOOK], { input, encoding: 'utf8' });
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  if (!result.stdout.trim()) return { decision: 'approve', reason: '' };
  const { hookSpecificOutput: out } = JSON.parse(result.stdout);
  assert.equal(out.hookEventName, 'PreToolUse');
  return { decision: out.permissionDecision, reason: out.permissionDecisionReason };
}

const run = (command, cwd) => runRaw(JSON.stringify({ tool_input: { command }, cwd }));

const onDefault = fixture('main');
const onFeature = fixture('feature/x');

test('on the default branch, a commit or a push asks for confirmation', () => {
  for (const command of ['git commit -m "wip"', 'git push', 'git commit -am "wip" && git push']) {
    const { decision, reason } = run(command, onDefault);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /default branch/, command);
  }
});

test('the action in the reason names what the command actually does', () => {
  assert.match(run('git commit -m "wip"', onDefault).reason, /direct commit here/);
  assert.match(run('git push origin main', onDefault).reason, /direct push here/);
  assert.match(run('git commit -m "wip" && git push', onDefault).reason, /direct commit and push here/);
});

test('a command that only mentions a verb is not a commit or a push', () => {
  // Regression: `git\b[^;&|]*\bcommit\b` matched the word anywhere after `git`, so read-only
  // commands prompted on the default branch.
  const readOnly = [
    'git log --grep=commit',
    'git config --global push.default simple',
    'git show --stat HEAD',
    'git log --oneline origin/main..HEAD',
    'ls -la',
    'echo push',
  ];
  for (const command of readOnly) {
    assert.equal(run(command, onDefault).decision, 'approve', command);
  }
});

test('a dry run changes nothing, so it is approved', () => {
  assert.equal(run('git push --dry-run', onDefault).decision, 'approve');
  assert.equal(run('git push --dry-run origin main', onFeature).decision, 'approve');
  assert.equal(run('git push -n origin main', onFeature).decision, 'approve');
  assert.equal(run('git push origin main --dry-run', onFeature).decision, 'approve');
});

test('a dry run does not cover a real push chained after it', () => {
  // Regression: `--dry-run` was tested against the whole line, so this whole call was approved.
  for (const command of [
    'git push --dry-run origin main && git push origin main',
    'git push --dry-run origin main; git push origin main',
    'git push --dry-run origin main | tee log.txt && git push origin main',
  ]) {
    assert.equal(run(command, onFeature).decision, 'ask', command);
  }
  // A bare `git push` reaches the default branch only from the default branch itself.
  for (const command of ['git push --dry-run && git push', 'git push --dry-run && git commit -m "wip"']) {
    assert.equal(run(command, onDefault).decision, 'ask', command);
  }
  assert.equal(run('git push --dry-run && git push', onFeature).decision, 'approve');
});

test('`-n` means --no-verify on a commit, not a dry run', () => {
  assert.equal(run('git commit -n -m "wip"', onDefault).decision, 'ask');
});

test('from a working branch, only a push that reaches the default branch asks', () => {
  const reaches = [
    'git push origin main',
    'git push -u origin main',
    'git push origin HEAD:main',
    'git push origin HEAD:refs/heads/main',
    'git push origin +main',
    'git push --set-upstream origin main',
    'git push --force-with-lease origin main',
  ];
  for (const command of reaches) {
    const { decision, reason } = run(command, onFeature);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /pushes to 'main'/, command);
  }

  const stays = [
    'git push',
    'git push -u origin feature/x',
    'git push origin feature/main-cleanup', // the name must be a whole ref part
    'git push origin main-line',
    'git commit -m "wip"',
    'git commit -m "push to main"', // the message is not a ref
    'git commit --amend --no-edit',
  ];
  for (const command of stays) {
    assert.equal(run(command, onFeature).decision, 'approve', command);
  }
});

test('a push of every ref asks, because no name matching can clear it', () => {
  // Regression: `--all` / `--mirror` never name the branch, so the token match could not see them.
  for (const command of ['git push --all origin', 'git push --mirror origin', 'git push --all']) {
    const { decision, reason } = run(command, onFeature);
    assert.equal(decision, 'ask', command);
    assert.match(reason, /every ref/, command);
  }
});

test('global options are skipped when reading the subcommand', () => {
  // The author's own push command: quoted values with spaces, two `-c` pairs before the verb.
  const real = "git -c credential.helper= -c credential.helper='!gh auth git-credential' push -u origin feature/x";
  assert.equal(run(real, onFeature).decision, 'approve');
  assert.equal(run(real.replace('feature/x', 'main'), onFeature).decision, 'ask');
  assert.equal(run('git --no-pager push origin main', onFeature).decision, 'ask');
  assert.equal(run('git.exe push origin main', onFeature).decision, 'ask');
});

test('`git -C` picks the repo the command really acts on', () => {
  // cwd sits on the default branch, `-C` points at the working-branch repo: no direct-commit prompt.
  assert.equal(run(`git -C ${onFeature} commit -m "wip"`, onDefault).decision, 'approve');
  // And the other way round.
  assert.match(run(`git -C ${onDefault} commit -m "wip"`, onFeature).reason, /default branch/);
});

test('a repo whose default branch is not main is handled by name', () => {
  const trunk = fixture('feature/y', 'release/v1');
  assert.match(run('git push origin release/v1', trunk).reason, /pushes to 'release\/v1'/);
  assert.equal(run('git push origin release/v2', trunk).decision, 'approve');
});

test('anything unusable is approved rather than blocking the work', () => {
  assert.equal(runRaw('').decision, 'approve');
  assert.equal(runRaw('not json at all').decision, 'approve');
  assert.equal(runRaw('{}').decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: {} })).decision, 'approve');
  assert.equal(run('git commit -m "wip"', join(tmpdir(), 'does-not-exist-guard')).decision, 'approve');
  assert.equal(run('git commit -m "wip"', tmpdir()).decision, 'approve'); // outside any repo
});
