#!/usr/bin/env node
/**
 * Tests for hooks/secret-scan.js. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * The hook does no I/O beyond stdin, so every case is a Write/Edit payload in and a decision out.
 *
 * Every credential-shaped fixture below is **assembled at run time** (`'ghp' + '_' + …`) instead of
 * written as a literal. Two reasons, and both are load-bearing: tools/validate.mjs scans this very
 * file for token shapes and would fail the build on a realistic literal, and a repository should
 * not contain strings that a scanner elsewhere will one day report as a real leak.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'secret-scan.js');

function runRaw(input) {
  const result = spawnSync(process.execPath, [HOOK], { input, encoding: 'utf8' });
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  if (!result.stdout.trim()) return { decision: 'approve', reason: '' };
  const { hookSpecificOutput: out } = JSON.parse(result.stdout);
  assert.equal(out.hookEventName, 'PreToolUse');
  return { decision: out.permissionDecision, reason: out.permissionDecisionReason };
}

/** A Write of `content` to `file_path`. */
const write = (content, file_path = 'src/App/appsettings.json') =>
  runRaw(JSON.stringify({ tool_input: { file_path, content } }));

/** An Edit replacing `old_string` with `new_string`. */
const edit = (new_string, old_string = 'placeholder', file_path = 'src/App/Program.cs') =>
  runRaw(JSON.stringify({ tool_input: { file_path, old_string, new_string } }));

function blocks(content, reasonPattern, file) {
  const { decision, reason } = write(content, file);
  assert.equal(decision, 'deny', content);
  assert.match(reason, reasonPattern, content);
  // The message is only useful if it says where to look.
  assert.match(reason, /line \d+:/, content);
}

const allows = (content, file) => assert.equal(write(content, file).decision, 'approve', content);

// ── Assembled fixtures: realistic shapes, no literal secret in the repo ───────────────────────

const A = 'A1b2C3d4E5f6G7h8';                   // 16 chars
const LONG = `${A}${A}${A.toLowerCase()}`;      // 48 chars
const providerToken = `ghp${'_'}${LONG}`;
const patToken = `github${'_'}pat${'_'}${LONG}`;
const slackToken = `xoxb${'-'}1234567890${'-'}${LONG}`;
const accessKeyId = `AKIA${'ABCDEFGHIJKLMNOP'}`;
const apiKey = `sk${'-'}ant${'-'}api03${'-'}${LONG}`;
const cloudKey = `AIza${'SyD'}${LONG.slice(0, 32)}`;
const jwt = `eyJ${LONG}.eyJ${LONG}.${LONG}`;
const accountKey = `${LONG}${LONG}==`;

// ── True positives ────────────────────────────────────────────────────────────────────────────

test('a provider token', () => {
  blocks(`const client = new Client("${providerToken}");`, /provider token/);
  blocks(`GH_TOKEN: ${patToken}`, /provider token/);
  blocks(`slackWebhookToken = "${slackToken}"`, /provider token/);
});

test('a cloud access key', () => {
  blocks(`aws_access_key_id = ${accessKeyId}`, /cloud access key id/);
  blocks(`  "GoogleMapsKey": "${cloudKey}"`, /cloud API key/);
  blocks(`AccountKey=${accountKey};EndpointSuffix=core.windows.net`, /cloud access key in a connection string/);
  blocks(`aws_secret_access_key=${LONG}`, /cloud access key in a connection string/);
  blocks(`ClientSecret=${LONG}`, /cloud access key in a connection string/);
});

test('an API-key-shaped provider secret', () => {
  blocks(`ANTHROPIC_API_KEY=${apiKey}`, /API-key-shaped string/);
});

test('a connection string carrying a password', () => {
  blocks(
    '"Default": "Server=localhost,1433;Database=Sales;User Id=sa;Password=Str0ngLocalPass;"',
    /password in a connection string/,
  );
  blocks('ConnectionStrings__Default=Host=db;Username=app;Pwd=Str0ngLocalPass', /password in a connection string/);
});

test('a private key block', () => {
  blocks('-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA\n-----END RSA PRIVATE KEY-----', /private key block/);
  blocks('-----BEGIN PRIVATE KEY-----', /private key block/);
  blocks('-----BEGIN OPENSSH PRIVATE KEY-----', /private key block/);
});

test('a signed token', () => {
  blocks(`Authorization: Bearer ${jwt}`, /signed token/);
});

test('an Edit is scanned on the text it introduces, not the text it removes', () => {
  const { decision, reason } = edit(`var token = "${providerToken}";`);
  assert.equal(decision, 'deny');
  assert.match(reason, /provider token/);
  // The removed text is never the hook's business: taking a secret *out* must always be allowed.
  assert.equal(
    runRaw(JSON.stringify({
      tool_input: {
        file_path: 'src/App/Program.cs',
        old_string: `var token = "${providerToken}";`,
        new_string: 'var token = Environment.GetEnvironmentVariable("GH_TOKEN");',
      },
    })).decision,
    'approve',
  );
});

test('the message names the pattern and the line, and never echoes the whole secret', () => {
  const { reason } = write(`# header\n# notes\nAPI_TOKEN=${providerToken}\n`);
  assert.match(reason, /line 3:/);
  assert.match(reason, /provider token/);
  assert.ok(!reason.includes(providerToken), 'the credential itself must not be echoed in full');
  assert.match(reason, /chars\)/, 'the redacted form states the length');
});

// ── False positives: the half that decides whether the hook is bearable ───────────────────────

test('a placeholder is not a credential', () => {
  allows('"Default": "Server=localhost;Database=Sales;User Id=sa;Password=<your-password>;"');
  allows('Password=changeme');
  allows('Password=CHANGE_ME');
  allows('DB_PASSWORD=your-password-here');
  allows('AccountKey=***REDACTED***');
  allows('Password=xxxxxxxx');
  allows('Password=TODO');
  allows('Password=');
  allows('"Password": ""');
});

test('an example value is not a credential', () => {
  allows('# Password=examplePassword123 (copy this file to appsettings.Development.json)');
  allows('Password=sample-password-value');
  allows('AccountKey=exampleAccountKeyValueGoesHere');
  allows('# e.g. Password=myPasswordSample', 'docs/setup.md');
});

test('a variable reference is not a credential', () => {
  allows('$connection = "Server=db;Password=$env:DB_PASSWORD;"');
  allows('ConnectionStrings__Default=Server=db;Password=${DB_PASSWORD}');
  allows('connection = f"Host=db;Password={db_password}"');
  allows('Password=%DB_PASSWORD%');
  allows('var cs = $"Server=db;Password={settings.DbPassword}";');
  allows('cs = "Server=db;Password=" + password;');
  allows("cs = 'Server=db;Password=' + password");
  allows('Password=@Model.DbPassword');
  allows('Password=DB_PASSWORD');
  allows('password: {{ .Values.db.password }}');
});

test('a detection pattern is not the thing it detects', () => {
  // The exact shapes a scanner, a test and a grep recipe must be free to contain.
  allows('const LEAK = /\\b(?:password|pwd)\\s*=\\s*[^;\'"\\s|]{3,}/gi;');
  allows('grep -rn "Password=" ./src');
  allows('Select-String -Path .\\src\\*.json -Pattern "AccountKey="');
  allows('rg -n "AKIA[0-9A-Z]{16}" .');
  allows(`const fixture = "AKIA" + "${'ABCDEFGHIJKLMNOP'}";`);
});

test('a scanner file is skipped whole, or the hook would lock itself', () => {
  const scanners = ['hooks/secret-scan.js', 'tools/secret-scan.test.mjs', 'tools/validate.mjs'];
  for (const file of scanners) {
    assert.equal(write(`const token = "${providerToken}";`, file).decision, 'approve', file);
  }
  // A normal file with the same content is still blocked.
  assert.equal(write(`const token = "${providerToken}";`, 'src/App/Client.cs').decision, 'deny');
});

test('ordinary content stays silent', () => {
  const quiet = [
    '"Default": "Server=localhost,1433;Database=Sales;Trusted_Connection=True;TrustServerCertificate=True"',
    'public async Task<IActionResult> GetOrders(CancellationToken ct) => Ok(await _svc.List(ct));',
    '{ "Logging": { "LogLevel": { "Default": "Information" } } }',
    'export const API_BASE = "/api/v1";',
    'const id = "3fa85f64-5717-4562-b3fc-2c963f66afa6";',
    '## Setup\n\nRun `docker compose up -d`, then `dotnet ef database update`.',
  ];
  for (const content of quiet) allows(content);
});

test('anything unusable lets the write through rather than blocking the work', () => {
  assert.equal(runRaw('').decision, 'approve');
  assert.equal(runRaw('not json at all').decision, 'approve');
  assert.equal(runRaw('{}').decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: {} })).decision, 'approve');
  assert.equal(runRaw(JSON.stringify({ tool_input: { file_path: 'a.txt', content: '   ' } })).decision, 'approve');
});
