#!/usr/bin/env node
/**
 * Tests for hooks/session-brief.js. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * The hook reads branch, commit and upstream straight out of `.git`, so the fixtures fabricate
 * that directory rather than creating real repositories — hermetic, and no `git` invocation of the
 * suite's own. `git status` is the hook's single subprocess and it fails against a fabricated
 * repository, which is exactly the degraded path worth pinning: every line the hook cannot
 * determine must simply be absent.
 *
 * Each test points CLAUDE_CONFIG_DIR at its own temp directory, so no case can read or dirty the
 * real cache — or another case's.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'session-brief.js');
const SHA = 'a1b2c3d4'.repeat(5);
const OTHER = 'f0e1d2c3'.repeat(5);
const WHEN = Math.floor(Date.now() / 1000) - 3600;   // an hour ago
const created = [];

function temp(prefix) {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  created.push(dir);
  return dir;
}

process.on('exit', () => {
  for (const root of created) {
    try { rmSync(root, { recursive: true, force: true }); } catch { /* tmp, let the OS have it */ }
  }
});

/**
 * A repository checked out on `branch` (or detached at `sha` when branch is null), with the
 * optional pieces the hook reads: an upstream in the config, a reflog, a loose commit object.
 */
function repo({ branch = 'feature/4211-orders', sha = SHA, upstream = 'origin', reflog, object } = {}) {
  const root = temp('brief-');
  const gitDir = join(root, '.git');
  mkdirSync(gitDir, { recursive: true });

  if (branch) {
    writeFileSync(join(gitDir, 'HEAD'), `ref: refs/heads/${branch}\n`);
    const ref = join(gitDir, 'refs', 'heads', branch);
    mkdirSync(dirname(ref), { recursive: true });     // `feature/x` is a nested path
    writeFileSync(ref, `${sha}\n`);
  } else {
    writeFileSync(join(gitDir, 'HEAD'), `${sha}\n`);
  }

  if (branch && upstream) {
    writeFileSync(join(gitDir, 'config'), [
      '[core]',
      '\tbare = false',
      `[remote "${upstream}"]`,
      `\turl = https://host.invalid/org/project`,
      `[branch "${branch}"]`,
      `\tremote = ${upstream}`,
      `\tmerge = refs/heads/${branch}`,
      '',
    ].join('\n'));
  }

  if (reflog) {
    mkdirSync(join(gitDir, 'logs'), { recursive: true });
    writeFileSync(join(gitDir, 'logs', 'HEAD'), reflog);
  }

  if (object) {
    // A real loose object: `commit <len>\0<headers>\n\n<message>`, zlib-deflated, stored under
    // objects/<first two of the sha>/<the rest>. The hook never verifies the hash, so the fixture
    // can choose it.
    const body = `tree ${OTHER}\nauthor Dev <dev@example.com> ${WHEN} +0000\n`
      + `committer Dev <dev@example.com> ${WHEN} +0000\n\n${object}\n`;
    const raw = Buffer.concat([Buffer.from(`commit ${body.length}\0`), Buffer.from(body)]);
    mkdirSync(join(gitDir, 'objects', sha.slice(0, 2)), { recursive: true });
    writeFileSync(join(gitDir, 'objects', sha.slice(0, 2), sha.slice(2)), deflateSync(raw));
  }

  return root;
}

/**
 * Run the hook against `cwd`, with its own cache directory. Returns the brief's lines.
 *
 * `spawnCwd` matters for the malformed-payload cases: with no usable `cwd` in the payload the hook
 * falls back to the process working directory, which would otherwise be this repository.
 */
function run(cwd, configDir = temp('brief-cfg-'), raw, spawnCwd = temp('brief-nowhere-')) {
  const input = raw ?? JSON.stringify({ hook_event_name: 'SessionStart', source: 'startup', cwd });
  const result = spawnSync(process.execPath, [HOOK], {
    input,
    encoding: 'utf8',
    cwd: spawnCwd,
    env: { ...process.env, CLAUDE_CONFIG_DIR: configDir },
  });
  assert.equal(result.status, 0, 'the hook must always exit 0, whatever happens');
  if (!result.stdout.trim()) return [];
  const { hookSpecificOutput: out } = JSON.parse(result.stdout);
  assert.equal(out.hookEventName, 'SessionStart');
  return out.additionalContext.split('\n');
}

const REFLOG = (message) =>
  `${'0'.repeat(40)} ${SHA} Dev <dev@example.com> ${WHEN} +0000\t${message}\n`;

test('the brief names the branch, the last commit, the upstream and the work item', () => {
  const lines = run(repo({ object: 'Add the order list projection' }));
  assert.equal(lines.length, 4);
  assert.match(lines[0], /^branch feature\/4211-orders/);
  assert.match(lines[1], /^last a1b2c3d Add the order list projection \(1h ago\)$/);
  assert.match(lines[2], /^origin\/feature\/4211-orders/);
  assert.equal(lines[3], 'work item #4211 (from the branch name)');
});

test('never more than five lines', () => {
  const cfg = temp('brief-cfg-');
  const root = repo({ object: 'Add the order list projection' });
  // Seed a stale entry carrying a PR, so every one of the five lines can be produced at once.
  writeFileSync(join(cfg, '.session-brief-cache.json'), JSON.stringify({
    [join(root, '.git')]: { at: 0, lines: [], pr: { number: 128, title: 'Add the order list' } },
  }));
  const lines = run(root, cfg);
  assert.equal(lines.length, 5);
  assert.ok(lines.some((l) => l === 'open PR !128 Add the order list'), lines.join(' | '));
});

test('the last commit falls back to the reflog once the object is packed away', () => {
  const lines = run(repo({ reflog: REFLOG('commit: Split the order query') }));
  assert.match(lines[1], /^last a1b2c3d Split the order query \(1h ago\)$/);
});

test('a reflog entry that is not a commit is not reported as one', () => {
  // `checkout: moving from main to feature/x` says nothing about what was committed.
  const lines = run(repo({ reflog: REFLOG('checkout: moving from main to feature/4211-orders') }));
  assert.ok(!lines.some((l) => l.startsWith('last ')), lines.join(' | '));
});

test('a branch with no upstream says so, instead of implying it is in step', () => {
  const lines = run(repo({ upstream: null, object: 'Start the spike' }));
  assert.ok(lines.includes('no upstream configured — a push needs an explicit remote and branch'), lines.join(' | '));
});

test('a detached HEAD is reported as one', () => {
  const lines = run(repo({ branch: null, object: 'Bisect point' }));
  assert.match(lines[0], /^detached HEAD at a1b2c3d$/);
  assert.ok(!lines.some((l) => l.includes('work item')), 'no branch name, no work item');
});

test('a branch name with no id carries no work-item line', () => {
  const lines = run(repo({ branch: 'feature/order-list', object: 'Add the order list' }));
  assert.ok(!lines.some((l) => l.includes('work item')), lines.join(' | '));
});

test('the work-item id is read from every branch shape the convention allows', () => {
  const shapes = [
    ['feature/4211-order-list', '4211'],
    ['fix/4211', '4211'],
    ['feature/AB#4211-orders', '4211'],
    ['feature/4211_orders', '4211'],
  ];
  for (const [branch, id] of shapes) {
    const lines = run(repo({ branch }));
    assert.ok(
      lines.includes(`work item #${id} (from the branch name)`),
      `${branch} -> ${lines.join(' | ')}`,
    );
  }
});

test('a second session inside the TTL is served from the cache', () => {
  const cfg = temp('brief-cfg-');
  const root = repo({ object: 'Add the order list projection' });
  const first = run(root, cfg);
  assert.ok(existsSync(join(cfg, '.session-brief-cache.json')), 'the snapshot is persisted');

  // Move the repository to another branch. A recomputed brief would follow; a cached one must not.
  writeFileSync(join(root, '.git', 'HEAD'), 'ref: refs/heads/feature/9999-other\n');
  assert.deepEqual(run(root, cfg), first, 'inside the TTL the brief is the cached snapshot');
});

test('outside a repository the hook prints nothing at all', () => {
  assert.deepEqual(run(temp('brief-plain-')), []);
});

test('a fact that cannot be determined is left out, never guessed', () => {
  // Nothing but HEAD: no ref, no config, no reflog, no object.
  const root = temp('brief-bare-');
  mkdirSync(join(root, '.git'), { recursive: true });
  writeFileSync(join(root, '.git', 'HEAD'), 'ref: refs/heads/feature/x\n');
  const lines = run(root);
  assert.deepEqual(lines, [
    'branch feature/x',
    'no upstream configured — a push needs an explicit remote and branch',
  ]);
});

test('anything unusable prints nothing rather than an error', () => {
  const cfg = temp('brief-cfg-');
  for (const raw of ['', 'not json at all', '{}', JSON.stringify({ cwd: '' })]) {
    assert.deepEqual(run(null, cfg, raw), [], JSON.stringify(raw));
  }
  assert.deepEqual(run(null, cfg, JSON.stringify({ cwd: join(tmpdir(), 'does-not-exist-brief') })), []);
});

test('a payload with no cwd falls back to the process working directory', () => {
  // Claude Code always sends `cwd`; the fallback is what keeps the hook useful if it ever does not.
  const root = repo({ object: 'Add the order list projection' });
  assert.match(run(null, temp('brief-cfg-'), '{}', root)[0], /^branch feature\/4211-orders/);
});
