#!/usr/bin/env node
/**
 * Tests for hooks/worklog-pending.js. Zero dependencies — `node:test` on Node 18+.
 *
 *   node --test "tools/*.test.mjs"
 *
 * The hook reads history.jsonl and the /worklog audit from CLAUDE_CONFIG_DIR, so every case gets
 * its own temp directory holding a fabricated history — hermetic, and never the real cache. The
 * workspace roots come from the environment, which is the part worth pinning: unset must mean
 * silence, never a reminder built on a guessed path.
 *
 * Generated by Claude Code at the user's request.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HOOK = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'worklog-pending.js');
const ROOT = 'D:\\work\\';
const created = [];

process.on('exit', () => {
  for (const dir of created) {
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* tmp, let the OS have it */ }
  }
});

const pad = (n) => String(n).padStart(2, '0');
const iso = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

/** The most recent past weekday still inside the hook's window (month, or week reaching back). */
function pendingCandidate() {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const weekStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() + 6) % 7));
  const since = Math.min(monthStart.getTime(), weekStart.getTime());
  const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 10);
  while (d.getTime() >= since) {
    if (d.getDay() !== 0 && d.getDay() !== 6) return d;
    d.setDate(d.getDate() - 1);
  }
  return null;
}

const DAY = pendingCandidate();

/** A config dir with `prompts` history lines per project on DAY, and an optional audit. */
function config({ projects = [`${ROOT}product\\api`], prompts = 3, audit } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'wlp-'));
  created.push(dir);
  const lines = [];
  for (const project of projects) {
    for (let i = 0; i < prompts; i++) lines.push(JSON.stringify({ timestamp: DAY.getTime() + i, project }));
  }
  writeFileSync(join(dir, 'history.jsonl'), `${lines.join('\n')}\n`);
  if (audit) {
    mkdirSync(join(dir, 'worklog'));
    writeFileSync(join(dir, 'worklog', 'pushed.json'), JSON.stringify(audit));
  }
  return dir;
}

function run(dir, env = {}) {
  const r = spawnSync(process.execPath, [HOOK], {
    encoding: 'utf8',
    env: { ...process.env, CLAUDE_WORKSPACE_ROOTS: '', CLAUDE_WORKSPACE_NESTED: '', ...env, CLAUDE_CONFIG_DIR: dir },
  });
  assert.equal(r.status, 0, r.stderr);
  return r.stdout ? JSON.parse(r.stdout).hookSpecificOutput.additionalContext : '';
}

const skip = DAY ? false : 'no past weekday inside the window today';

test('roots unset → silent, however much work the history shows', { skip }, () => {
  assert.equal(run(config()), '');
});

test('a worked day under a root, with no audit → named in the reminder', { skip }, () => {
  const out = run(config(), { CLAUDE_WORKSPACE_ROOTS: ROOT });
  assert.match(out, new RegExp(`${iso(DAY)} \\(product\\)`));
});

test('roots match case- and slash-insensitively, trailing separator optional', { skip }, () => {
  const out = run(config(), { CLAUDE_WORKSPACE_ROOTS: 'd:/WORK' });
  assert.match(out, new RegExp(iso(DAY)));
});

test('a nested root labels the subfolder and drops the bare root', { skip }, () => {
  const dir = config({ projects: [`${ROOT}clients\\acme\\repo`, `${ROOT}clients`] });
  const out = run(dir, { CLAUDE_WORKSPACE_ROOTS: ROOT, CLAUDE_WORKSPACE_NESTED: 'clients' });
  assert.match(out, /\(clients\/acme\)/);
});

test('an audit entry covering the day closes it, zero hours included', { skip }, () => {
  const audit = [{ periodFrom: iso(DAY), periodTo: iso(DAY), hoursLogged: 0 }];
  assert.equal(run(config({ audit }), { CLAUDE_WORKSPACE_ROOTS: ROOT }), '');
});

test('work outside every root is tooling, not pending', { skip }, () => {
  assert.equal(run(config({ projects: ['C:\\tools\\x'] }), { CLAUDE_WORKSPACE_ROOTS: ROOT }), '');
});

test('fewer than three prompts is a check-in, not a working day', { skip }, () => {
  assert.equal(run(config({ prompts: 2 }), { CLAUDE_WORKSPACE_ROOTS: ROOT }), '');
});

test('the snapshot for the statusline is written either way', { skip }, () => {
  const dir = config();
  run(dir);
  assert.ok(existsSync(join(dir, '.worklog-pending.json')));
});
